
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_stats_Source
#define SOM_Module_stats_Source
#endif
#define stats_Class_Source
#define M_stats_Class_Source

#define MAXSTACKSIZE  65536
#define GLMAXPATH  1024

#include "stats.ih"


typedef struct CData
   {
   HWND hwndF;
   HWND hwndDlg;
   CHAR dTopFold[GLMAXPATH];
   CHAR ftitle[GLMAXPATH];
   }CBD;
typedef CBD FAR *PFCBD;

typedef struct _DLGDATAFOLD
   {
   CHAR title[GLMAXPATH];
   CHAR fnameStr[GLMAXPATH];
   CHAR fsizeStr[GLMAXPATH];
   CHAR ftimeStr[GLMAXPATH];
   CHAR fdateStr[GLMAXPATH];
   CHAR dirStr[40];
   }DLGDATAFOLD;
typedef DLGDATAFOLD FAR *PFDLGDATAFOLD;

typedef struct _DLGDATA
   {
   CHAR title[GLMAXPATH];
   CHAR fnameStr[GLMAXPATH];
   CHAR fsizeStr[GLMAXPATH];
   CHAR ftimeStr[GLMAXPATH];
   CHAR fdateStr[GLMAXPATH];
   CHAR fdateStrLC[GLMAXPATH];
   CHAR ftimeStrLC[GLMAXPATH];
   CHAR fdateStrLA[GLMAXPATH];
   CHAR ftimeStrLA[GLMAXPATH];
   CHAR eaStr[GLMAXPATH];
   ULONG attrF;
   }DLGDATA;
typedef DLGDATA FAR *PFDLGDATA;

DLGDATA dlgdat;
int dtWidth, dtHeight;
HMODULE hResource;
ULONG totFS;
ULONG bootDrive;
INT pgmData[60];
BOOL STATSBUSY;
ULONG totFiles;
ULONG bytesTotF;
CHAR STATSINI[GLMAXPATH]; 
CHAR DTOP[GLMAXPATH];
ULONG dtopsize = sizeof(DTOP);
BOOL    WAITAHOTSECDEL;
BOOL    WAITAHOTSECADD;
BOOL    WAITAHOTSECDELRD;
BOOL    WAITAHOTSECADDRD;
BOOL    DESKTOPOPEN;
BOOL    DISKSREADY;                                             
BOOL SBUSY, TSBUSY;
INT TOTDIRS;
CHAR SCODE[GLMAXPATH];





VOID debugMsgCH(CHAR ch, CHAR *varName);
VOID debugMsgStr(CHAR *str, CHAR *varName);
VOID debugMsgULong(ULONG num, CHAR *varName);
VOID debugMsgInt(INT num, CHAR *varName);
VOID msgBox(HWND hwnd, CHAR *title, CHAR *message);
INT msgBoxOKCANCEL(HWND hwndDlg, CHAR *title, CHAR *msg);


VOID _Optlink getINIFQNAME(PVOID n);
VOID _Optlink payUp(PVOID n);
INT chkreg(VOID);
VOID saveSet(VOID);
VOID querySet(VOID);
ULONG findFiles(CHAR *curPath);
ULONG findDirList(CHAR *pcCurrentPath);
char * strinsert(char *s, char insert);
INT addComa(CHAR *numstr);
VOID _Optlink aboutStats(PVOID n);
VOID _Optlink statsSettings(PVOID n);
VOID _Optlink showTreeStats(PVOID n);
VOID _Optlink showFolderStats(PVOID n);
VOID _Optlink setFWinStats(PVOID nfdat);
VOID _Optlink setDiskWinStats(PVOID n);
INT searchPDirs(CHAR *schpath);
INT searchP(CHAR *schpath);
VOID _Optlink addNotify(PVOID n);
VOID _Optlink deleteNotify(PVOID n);
VOID _Optlink showFileStats(PVOID n);
INT isOpenFold(stats *somSelf);
VOID setFolderStats(SOMAny *sSelf, HWND hwndF);
VOID setFolderStatsRD(SOMAny *sSelf, HWND hwndF);
INT getObjCount(SOMAny *sSelf, CHAR *dTopFold);
BOOL setConMenu( HWND hmenu, USHORT msg);
MRESULT EXPENTRY fileStatsProc(HWND hwndDlg, ULONG msg,
                                                MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY statsProcF(HWND hwndDlg, ULONG msg,
                                             MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY statsProcP(HWND hwndDlg, ULONG msg,
                                             MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY statsSetProc(HWND hwndDlg, ULONG msg,
                                                MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY aboutStatsProc(HWND hwndDlg, ULONG msg,
                                                   MPARAM mp1, MPARAM mp2 );






// ****************************************************
// ****************************************************
// ****************************************************
// ****************************************************
// ******************* FOLDERS *************************
// ****************************************************
// ****************************************************
// ****************************************************







SOM_Scope BOOL  SOMLINK statsX_wpModifyPopupMenu(stats *somSelf, 
                                                 HWND hwndMenu, 
                                                 HWND hwndCnr, 
                                                 ULONG iPosition)
{
    BOOL HASFOLD;


    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpModifyPopupMenu");


    stats_parent_WPFolder_wpModifyPopupMenu(somSelf, 
                                                    hwndMenu, 
                                                    hwndCnr, 
                                                    iPosition);
                                                    
    querySet();
            
    if( _somIsA(somSelf, _WPDesktop) )
       {
       if( pgmData[0] == 1 || pgmData[1] == 1 )
          {
          _wpInsertPopupMenuItems(somSelf,
                                               hwndMenu,
                                               0,
                                               hResource,
                                               IDM_STATSMAINNS,
                                               WPMENUID_PRIMARY);
          setConMenu(hwndMenu, ID_STATSMAIN);
          }
       else
          {   
          _wpInsertPopupMenuItems(somSelf,
                                               hwndMenu,
                                               0,
                                               hResource,
                                               IDM_STATSMAIN,
                                               WPMENUID_PRIMARY);
          setConMenu(hwndMenu, ID_STATSMAIN);
          }
       }
    else
       { 
       if( pgmData[0] == 0 )
          {                                                        
          if( pgmData[1] == 0 )
             {
             _wpContainsFolders(somSelf, &HASFOLD);
             if( HASFOLD )
                {
                _wpInsertPopupMenuItems(somSelf,
                                                     hwndMenu,
                                                     0,
                                                     hResource,
                                                     IDM_STATSFOLDER,
                                                     WPMENUID_PRIMARY);
                setConMenu(hwndMenu, ID_STATSFOLDER);
                }                                     
             else       
                {                
                _wpInsertPopupMenuItems(somSelf,
                                                     hwndMenu,
                                                     0,
                                                     hResource,
                                                     IDM_STATSFOLDERNF,
                                                    WPMENUID_PRIMARY);
                }
             }   
          }      
       }                                     
                                         
    return(TRUE);                                                    
}





SOM_Scope BOOL  SOMLINK statsX_wpMenuItemSelected(stats *somSelf, 
                                                  HWND hwndFrame, 
                                                  ULONG ulMenuId)
{
    static CBD zfd;
    BOOL result;

    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpMenuItemSelected");

    result = FALSE;
    
    switch( ulMenuId )
       {
       case ID_STATSMAIN :
       case ID_SSTATSMAIN :
          {
           _beginthread(statsSettings, NULL, MAXSTACKSIZE, (PVOID)0);
          }
          break;
          
       case ID_SSTATSABOUT :
           _beginthread(aboutStats, NULL, MAXSTACKSIZE, (PVOID)0);
          break;
          
       case ID_DTFSTATS :
       case ID_SSTATSFOLDER :
       case ID_STATSFOLDER :
          {
          _beginthread(showFolderStats, NULL, MAXSTACKSIZE, (PVOID)somSelf);
           if( chkreg() == 0 )
              _beginthread(payUp, NULL, MAXSTACKSIZE, (PVOID)0);
          }
          break;
       
       case ID_DTTSTATS :
       case ID_SSTATSTREE :
          _beginthread(showTreeStats, NULL, MAXSTACKSIZE, (PVOID)somSelf);
          break;
       
       default :
          result = stats_parent_WPFolder_wpMenuItemSelected(somSelf, hwndFrame, ulMenuId);
          break;
       }   
     
    return(result); 
    // return (stats_parent_WPFolder_wpMenuItemSelected(somSelf, hwndFrame, ulMenuId));
}






SOM_Scope HWND  SOMLINK statsX_wpViewObject(stats *somSelf, HWND hwndCnr, 
                                            ULONG ulView, ULONG param)
{
    HWND hwndF;
    CHAR ona[GLMAXPATH];
    ULONG onasize = sizeof(ona);
    
    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpViewObject");

    hwndF = stats_parent_WPFolder_wpViewObject(somSelf, hwndCnr, 
                                                                       ulView, param);
                                                                       

    querySet();
    if( pgmData[0] == 0 )
       {
       if( pgmData[3] == 0 )
          {
          _wpQueryRealName(somSelf, ona, &onasize, TRUE);
          _wpQueryRealName(_wpclsQueryActiveDesktop(_WPDesktop),
                                      DTOP, &dtopsize, TRUE);
       
          if( stricmp(ona, DTOP) != 0 )
             {
             zString cn;
       
       
             cn = _somGetClassName(somSelf);
             if( (strcmpi(cn, "WPDesktop") != 0)  && (strcmpi(cn, "VPForm") != 0)  && (strcmpi(cn, "VPCForm") != 0)  && 
                 (strcmpi(cn, "VPCPForm") != 0)  && (strcmpi(cn, "IWFProject") != 0)  && (strcmpi(cn, "IWFQuickStart") != 0)  && 
                 (strcmpi(cn, "IWFRouter") != 0) && (strcmpi(cn, "FIMFolder") != 0)  && (strcmpi(cn, "TSEnhDrives") != 0) && 
                 (strcmpi(cn, "TSMasterSetup") != 0) && (strcmpi(cn, "TSZipElem") != 0)  && (strcmpi(cn, "TSZipMgr") != 0) && 
                 (strcmpi(cn, "TSTaskMgr") != 0) && (strcmpi(cn, "TSZooElem") != 0)  && (strcmpi(cn, "TSZooMgr") != 0) && 
                 (strcmpi(cn, "TSKeyDefn") != 0) && (strcmpi(cn, "TSLHAElem") != 0)  && (strcmpi(cn, "TSHAMgr") != 0) && 
                 (strcmpi(cn, "TSPackageElem") != 0) && (strcmpi(cn, "TSPackageFile") != 0)  && (strcmpi(cn, "TSFldrParent") != 0) && 
                 (strcmpi(cn, "TSCPad") != 0) && (strcmpi(cn, "TSTabFolder") != 0) && (strcmpi(cn, "TSKeyLaunch") != 0) )
                 {
                 _beginthread(setFWinStats, NULL, MAXSTACKSIZE, (PVOID)hwndF);
                 if( chkreg() == 0 )
                    _beginthread(payUp, NULL, MAXSTACKSIZE, (PVOID)0);
                 }
              }   
          }
       }   
                                                                       

    return(hwndF);                                                                       
}





SOM_Scope HWND  SOMLINK statsX_wpOpen(stats *somSelf, HWND hwndCnr, 
                                      ULONG ulView, ULONG param)
{
    HWND hwndDT;
    

    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpOpen");

    hwndDT = stats_parent_WPFolder_wpOpen(somSelf, hwndCnr, ulView, param);
                                         
    if(_somIsA(somSelf, _WPDesktop))
       {
       DESKTOPOPEN = TRUE;    
       _beginthread(getINIFQNAME, NULL, MAXSTACKSIZE, (PVOID)0);
       }

    return(hwndDT);
}




SOM_Scope BOOL  SOMLINK statsX_wpAddToContent(stats *somSelf, 
                                              WPObject* Object)
{
   BOOL added;
   PVIEWITEM prt;

    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpAddToContent");


    added = stats_parent_WPFolder_wpAddToContent(somSelf, Object);

    if( pgmData[0] == 0 )
       {
       if( pgmData[3] == 0 )
          {
          prt = _wpFindViewItem(somSelf, VIEW_CONTENTS, NULL);
     
          if( prt && added && !WAITAHOTSECADD )
             {
             zString cn;
       
       
             cn = _somGetClassName(somSelf);
             if( cn != NULL && strlen(cn) > 0 )
                {
                if( (strcmpi(cn, "WPDesktop") != 0)  && (strcmpi(cn, "VPForm") != 0)  && (strcmpi(cn, "VPCForm") != 0)  && 
                  (strcmpi(cn, "VPCPForm") != 0)  && (strcmpi(cn, "IWFProject") != 0)  && (strcmpi(cn, "IWFQuickStart") != 0)  && 
                  (strcmpi(cn, "IWFRouter") != 0) && (strcmpi(cn, "FIMFolder") != 0)  && (strcmpi(cn, "TSEnhDrives") != 0) && 
                  (strcmpi(cn, "TSMasterSetup") != 0) && (strcmpi(cn, "TSZipElem") != 0)  && (strcmpi(cn, "TSZipMgr") != 0) && 
                  (strcmpi(cn, "TSTaskMgr") != 0) && (strcmpi(cn, "TSZooElem") != 0)  && (strcmpi(cn, "TSZooMgr") != 0) && 
                  (strcmpi(cn, "TSKeyDefn") != 0) && (strcmpi(cn, "TSLHAElem") != 0)  && (strcmpi(cn, "TSHAMgr") != 0) && 
                  (strcmpi(cn, "TSPackageElem") != 0) && (strcmpi(cn, "TSPackageFile") != 0)  && (strcmpi(cn, "TSFldrParent") != 0) && 
                  (strcmpi(cn, "TSCPad") != 0) && (strcmpi(cn, "TSTabFolder") != 0) && (strcmpi(cn, "TSKeyLaunch") != 0) )
                   {
                   WAITAHOTSECADD = TRUE;
                   _beginthread(addNotify, NULL, MAXSTACKSIZE, (PVOID)somSelf);
                   }
                }
             }      
          }
       }   
    
   return(added);
   //  return (stats_parent_WPFolder_wpAddToContent(somSelf, Object));
}




SOM_Scope BOOL  SOMLINK statsX_wpDeleteFromContent(stats *somSelf, 
                                                   WPObject* Object)
{
    BOOL deleted;
    PVIEWITEM pcurt, pcurto;
    zString cn;
    
   
    /* statsData *somThis = statsGetData(somSelf); */
    statsMethodDebug("stats","statsX_wpDeleteFromContent");


    pcurt = _wpFindViewItem(somSelf, VIEW_CONTENTS, NULL);
   
    deleted = stats_parent_WPFolder_wpDeleteFromContent(somSelf, Object);

    if( pgmData[0] == 0 )
       {
       if( pgmData[3] == 0 )
          {
          if( deleted  && pcurt && (Object != somSelf) && !WAITAHOTSECDEL )
             {
             zString cn;
       
       
             cn = _somGetClassName(somSelf);
            if( (strcmpi(cn, "WPDesktop") != 0)  && (strcmpi(cn, "VPForm") != 0)  && (strcmpi(cn, "VPCForm") != 0)  && 
                 (strcmpi(cn, "VPCPForm") != 0)  && (strcmpi(cn, "IWFProject") != 0)  && (strcmpi(cn, "IWFQuickStart") != 0)  && 
                 (strcmpi(cn, "IWFRouter") != 0) && (strcmpi(cn, "FIMFolder") != 0)  && (strcmpi(cn, "TSEnhDrives") != 0) && 
                 (strcmpi(cn, "TSMasterSetup") != 0) && (strcmpi(cn, "TSZipElem") != 0)  && (strcmpi(cn, "TSZipMgr") != 0) && 
                 (strcmpi(cn, "TSTaskMgr") != 0) && (strcmpi(cn, "TSZooElem") != 0)  && (strcmpi(cn, "TSZooMgr") != 0) && 
                 (strcmpi(cn, "TSKeyDefn") != 0) && (strcmpi(cn, "TSLHAElem") != 0)  && (strcmpi(cn, "TSHAMgr") != 0) && 
                 (strcmpi(cn, "TSPackageElem") != 0) && (strcmpi(cn, "TSPackageFile") != 0)  && (strcmpi(cn, "TSFldrParent") != 0) && 
                 (strcmpi(cn, "TSCPad") != 0) && (strcmpi(cn, "TSTabFolder") != 0) && (strcmpi(cn, "TSKeyLaunch") != 0) )
                {
                pcurto = _wpFindViewItem(Object, VIEW_CONTENTS, NULL);
                if( !pcurto )
                   {
                   WAITAHOTSECDEL = TRUE; 
                   _beginthread(deleteNotify, NULL, MAXSTACKSIZE, (PVOID)somSelf);
                   }
                }
             }   
          }
       }   
   
    return(deleted);
    // return (stats_parent_WPFolder_wpDeleteFromContent(somSelf, Object));
}




SOM_Scope void  SOMLINK statsX_wpclsInitData(M_stats *somSelf)
{
    CHAR     szBuffer[BUFFERSIZE];
    
    /* M_statsData *somThis = M_statsGetData(somSelf); */
    M_statsMethodDebug("M_stats","statsX_wpclsInitData");

    if( hResource == NULLHANDLE )
       DosLoadModule(szBuffer,
                             BUFFERSIZE,
                             RESOURCE_MODULE,
                             &hResource); 

    WAITAHOTSECDEL = FALSE;    
    WAITAHOTSECADD = FALSE;    
    DESKTOPOPEN = FALSE;    
    DISKSREADY = FALSE; 
    SBUSY = FALSE;
    TSBUSY = FALSE;
                                                
    
    M_stats_parent_M_WPFolder_wpclsInitData(somSelf);
}






SOM_Scope void  SOMLINK statsX_wpclsUnInitData(M_stats *somSelf)
{
    /* M_statsData *somThis = M_statsGetData(somSelf); */
    M_statsMethodDebug("M_stats","statsX_wpclsUnInitData");

    M_stats_parent_M_WPFolder_wpclsUnInitData(somSelf);
}








// ****************************************************
// ****************************************************
// ****************************************************
// ****************************************************
// ********************* FILES *************************
// ****************************************************
// ****************************************************
// ****************************************************



SOM_Scope void  SOMLINK statsfileX_wpInitData(statsfile *somSelf)
{
    /* statsfileData *somThis = statsfileGetData(somSelf); */
    statsfileMethodDebug("statsfile","statsfileX_wpInitData");

    statsfile_parent_WPDataFile_wpInitData(somSelf);
}






SOM_Scope void  SOMLINK statsfileX_wpUnInitData(statsfile *somSelf)
{
    /* statsfileData *somThis = statsfileGetData(somSelf); */
    statsfileMethodDebug("statsfile","statsfileX_wpUnInitData");

    statsfile_parent_WPDataFile_wpUnInitData(somSelf);
}






SOM_Scope BOOL  SOMLINK statsfileX_wpModifyPopupMenu(statsfile *somSelf, 
                                                     HWND hwndMenu, 
                                                     HWND hwndCnr, 
                                                     ULONG iPosition)
{
    /* statsfileData *somThis = statsfileGetData(somSelf); */
    statsfileMethodDebug("statsfile","statsfileX_wpModifyPopupMenu");

    statsfile_parent_WPDataFile_wpModifyPopupMenu(somSelf, 
                                                          hwndMenu, 
                                                          hwndCnr, 
                                                          iPosition);
                                                          
    querySet();
    
    if( pgmData[0] == 0 )
       {
       if( pgmData[2] == 0 )
          {
          _wpInsertPopupMenuItems(somSelf,
                                               hwndMenu,
                                               0,
                                               hResource,
                                               IDM_STATSFILE,
                                               WPMENUID_PRIMARY);
          }                                     
       }                                     
                                         
   return(TRUE);                                                          
}






SOM_Scope BOOL  SOMLINK statsfileX_wpMenuItemSelected(statsfile *somSelf, 
                                                      HWND hwndFrame, 
                                                      ULONG ulMenuId)
{
    BOOL result;
    

    /* statsfileData *somThis = statsfileGetData(somSelf); */
    statsfileMethodDebug("statsfile","statsfileX_wpMenuItemSelected");

    result = TRUE;
   
    switch( ulMenuId )
       {
       case ID_STATSFILE :
          // DosBeep(100,100);
          _beginthread(showFileStats, NULL, MAXSTACKSIZE, (PVOID)somSelf);
           if( chkreg() == 0 )
              _beginthread(payUp, NULL, MAXSTACKSIZE, (PVOID)0);
          break;

       default:
          result = statsfile_parent_WPDataFile_wpMenuItemSelected(somSelf, 
                                                                                           hwndFrame, 
                                                                                           ulMenuId);
          break;
       }   
       
    return(result);
}







SOM_Scope void  SOMLINK statsfileX_wpclsInitData(M_statsfile *somSelf)
{
    CHAR     szBuffer[BUFFERSIZE];
    
    /* M_statsfileData *somThis = M_statsfileGetData(somSelf); */
    M_statsfileMethodDebug("M_statsfile","statsfileX_wpclsInitData");
 
    /*
    if( hResource == NULLHANDLE )
       DosLoadModule(szBuffer,
                             BUFFERSIZE,
                             RESOURCE_MODULE,
                             &hResource); 
    */
    DISKSREADY = FALSE;                                             

    M_statsfile_parent_M_WPDataFile_wpclsInitData(somSelf);
}






SOM_Scope void  SOMLINK statsfileX_wpclsUnInitData(M_statsfile *somSelf)
{
    /* M_statsfileData *somThis = M_statsfileGetData(somSelf); */
    M_statsfileMethodDebug("M_statsfile","statsfileX_wpclsUnInitData");

    M_statsfile_parent_M_WPDataFile_wpclsUnInitData(somSelf);
}








//*********************************************************
//*********************************************************
//*********************************************************
//*********************************************************
//*********************** DISKS ****************************
//*********************************************************
//*********************************************************






SOM_Scope BOOL  SOMLINK statsdiskX_wpModifyPopupMenu(statsdisk *somSelf, 
                                                     HWND hwndMenu, 
                                                     HWND hwndCnr, 
                                                     ULONG iPosition)
{
    /* statsdiskData *somThis = statsdiskGetData(somSelf); */
    statsdiskMethodDebug("statsdisk","statsdiskX_wpModifyPopupMenu");

    statsdisk_parent_WPDisk_wpModifyPopupMenu(somSelf, 
                                                                     hwndMenu, 
                                                                     hwndCnr, 
                                                                     iPosition);
           
    querySet();
            
    if( pgmData[0] == 0 )
       {                                                        
       if( pgmData[1] == 0 )
          {
          BOOL HASFOLD;
          CHAR dTopFold[GLMAXPATH];
          ULONG rsize = sizeof(dTopFold);
          ULONG drv;
          
          
          strcpy(dTopFold, " :\\");
          drv = _wpQueryLogicalDrive(somSelf);
          dTopFold[0] = (CHAR)(drv + '@');

          if( searchPDirs(dTopFold) > 0 )
             HASFOLD = TRUE;
          else
             HASFOLD = FALSE;
          if( HASFOLD )
             {
             _wpInsertPopupMenuItems(somSelf,
                                                  hwndMenu,
                                                  0,
                                                  hResource,
                                                  IDM_STATSFOLDERD,
                                                  WPMENUID_PRIMARY);
             setConMenu(hwndMenu, ID_STATSFOLDERD);
             }                                     
          else       
             {                
             _wpInsertPopupMenuItems(somSelf,
                                                  hwndMenu,
                                                  0,
                                                  hResource,
                                                  IDM_STATSFOLDERNFD,
                                                 WPMENUID_PRIMARY);
             }
          }   
       }
                
    return(TRUE);                                                      
}





SOM_Scope BOOL  SOMLINK statsdiskX_wpMenuItemSelected(statsdisk *somSelf, 
                                                      HWND hwndFrame, 
                                                      ULONG ulMenuId)
{
    BOOL result;
    SOMAny *ss;


    /* statsdiskData *somThis = statsdiskGetData(somSelf); */
    statsdiskMethodDebug("statsdisk","statsdiskX_wpMenuItemSelected");

    result = FALSE;
    
    switch( ulMenuId )
       {
       case ID_SSTATSFOLDERD :
       case ID_STATSFOLDERD :
          {
          ss = _wpQueryRootFolder(somSelf);
          if( ss )
             _beginthread(showFolderStats, NULL, MAXSTACKSIZE, (PVOID)ss);
          else
             msgBox(HWND_DESKTOP, "Attention!", "Drive not ready");   
          }
          break;
       
       case ID_SSTATSTREED :
          ss = _wpQueryRootFolder(somSelf);
          if( ss )
             _beginthread(showTreeStats, NULL, MAXSTACKSIZE, (PVOID)ss);
          else
             msgBox(HWND_DESKTOP, "Attention!", "Drive not ready");   
          break;
       
       
       default :
          result = statsdisk_parent_WPDisk_wpMenuItemSelected(somSelf, hwndFrame, ulMenuId);
          break;
       }   

    return(result);     
}





SOM_Scope HWND  SOMLINK statsdiskX_wpViewObject(statsdisk *somSelf, 
                                                HWND hwndCnr, 
                                                ULONG ulView, 
                                                ULONG param)
{
    HWND hwndF;

    /* statsdiskData *somThis = statsdiskGetData(somSelf); */
    statsdiskMethodDebug("statsdisk","statsdiskX_wpViewObject");


    hwndF = statsdisk_parent_WPDisk_wpViewObject(somSelf, hwndCnr, 
                                                 ulView, param);
                                                 
    if( pgmData[0] == 0 )
       {
       if( pgmData[3] == 0 )
          {
          if( hwndF != NULLHANDLE )
             {
             DISKSREADY = TRUE;                                             
             _beginthread(setDiskWinStats, NULL, MAXSTACKSIZE, (PVOID)hwndF);
             }
          }   
       }   

   return(hwndF);  

    // return (statsdisk_parent_WPDisk_wpViewObject(somSelf, hwndCnr, 
    //                                             ulView, param));
}





SOM_Scope void  SOMLINK statsdiskX_wpclsInitData(M_statsdisk *somSelf)
{
    /* M_statsdiskData *somThis = M_statsdiskGetData(somSelf); */
    M_statsdiskMethodDebug("M_statsdisk","statsdiskX_wpclsInitData");

    DISKSREADY = FALSE;                                             

    M_statsdisk_parent_M_WPDisk_wpclsInitData(somSelf);
}





SOM_Scope void  SOMLINK statsdiskX_wpclsUnInitData(M_statsdisk *somSelf)
{
    /* M_statsdiskData *somThis = M_statsdiskGetData(somSelf); */
    M_statsdiskMethodDebug("M_statsdisk","statsdiskX_wpclsUnInitData");

    M_statsdisk_parent_M_WPDisk_wpclsUnInitData(somSelf);
}








//*********************************************************
//*********************************************************
//*********************************************************
//*********************************************************
//********* EXTRA ROUTINES AND FUNCTIONS ****************
//*********************************************************
//*********************************************************






			      
VOID _Optlink aboutStats(PVOID n)
{
HAB habT;
HMQ hmqT;
HWND hwndF;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

hwndF = WinLoadDlg(HWND_DESKTOP,
                              HWND_DESKTOP,
                              aboutStatsProc,
                              hResource,
                              ID_ABOUTSTATSDLG, NULL);
                              
WinProcessDlg(hwndF);
   
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






MRESULT EXPENTRY aboutStatsProc(HWND hwndDlg, ULONG msg,
                                                   MPARAM mp1, MPARAM mp2 )
{
switch ( msg )
   {
   case WM_INITDLG:
      {
      POINTL mptl;
      LONG offx, offy, xx, yy;
      INT b, q;
      SWP swp;

       
       
      offx = 0;
      offy = 0;
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);  
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-80)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-80)+5) - dtWidth;
         }
      if( (mptl.x-(80+5)) < 0 )
         {
         offx = (mptl.x-(80+5)) ;
         }
      if( (mptl.y+(swp.cy-45)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(45+5)) < 0 )
         {
         offy = (mptl.y-(45+5));
         }

      xx = (mptl.x - 80) - offx;
      yy = (mptl.y - 45) - offy;
      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );

      }
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
        {
        case ID_ABOUTSTATSOK:
           WinDismissDlg(hwndDlg, FALSE);
           break;
           
        default :
           break;
        }
      break;

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}





VOID _Optlink statsSettings(PVOID n)
{
HAB habT;
HMQ hmqT;
HWND hwndF;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

hwndF = WinLoadDlg(HWND_DESKTOP,
                              HWND_DESKTOP,
                              statsSetProc,
                              hResource,
                              ID_STATSSETDLG,
                              (PVOID)0);
                              
WinProcessDlg(hwndF);
   
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






MRESULT EXPENTRY statsSetProc(HWND hwndDlg, ULONG msg,
                                                MPARAM mp1, MPARAM mp2 )
{
switch ( msg )
   {
   case WM_INITDLG:
      {
      POINTL mptl;
      LONG offx, offy, xx, yy;
      INT b, q;
      SWP swp;

       
       
      offx = 0;
      offy = 0;
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);  
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-80)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-80)+5) - dtWidth;
         }
      if( (mptl.x-(80+5)) < 0 )
         {
         offx = (mptl.x-(80+5)) ;
         }
      if( (mptl.y+(swp.cy-45)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(45+5)) < 0 )
         {
         offy = (mptl.y-(45+5));
         }

      xx = (mptl.x - 80) - offx;
      yy = (mptl.y - 45) - offy;
      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );
                      
      querySet();                
                      
      WinSendDlgItemMsg(hwndDlg, ID_STATSREGENTRY,EM_SETTEXTLIMIT,
                                  MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSetDlgItemText(hwndDlg, ID_STATSREGENTRY, SCODE);
      
      if( pgmData[1] )
             WinCheckButton(hwndDlg,ID_DISABLEFOLDTREEP,1);
                                       
      if( pgmData[2] )
             WinCheckButton(hwndDlg,ID_DISABLEFILEP,1);
                                       
      if( pgmData[3] )
             WinCheckButton(hwndDlg,ID_DISABLETB,1);
                                       
      if( pgmData[0] )
             {
             WinCheckButton(hwndDlg,ID_DISABLEALL,1);
             WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFOLDTREEP), FALSE);
             WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFILEP), FALSE);
             WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLETB), FALSE);
             }
                                       
      if( pgmData[4] )
             WinCheckButton(hwndDlg,ID_SHOWFILES,1);
                                       
      if( pgmData[5] )
             WinCheckButton(hwndDlg,ID_SHOWBYTES,1);
                                       
      if( pgmData[6] )
             WinCheckButton(hwndDlg,ID_SHOWDIRS,1);
                                       
      if( pgmData[7] )
             WinCheckButton(hwndDlg,ID_SHOWOBJS,1);
                                       
      if( pgmData[8] )
             WinCheckButton(hwndDlg,ID_SHOWPATH,1);
      
      switch( pgmData[9] )
         {
         case 0:
            WinCheckButton(hwndDlg,ID_USASTYLE,1);
            break;
            
         case 1:
            WinCheckButton(hwndDlg,ID_EUROPEANSTYLE,1);
            break;
            
         case 2:
            WinCheckButton(hwndDlg,ID_EUROPEANSTYLE2,1);
            break;
         }                                       

      if( pgmData[11] == 1 )
         WinCheckButton(hwndDlg, ID_NOSHOWFF,1);

      if( pgmData[11] == 2 )
         WinCheckButton(hwndDlg, ID_NOSHOWFFO,1);
            
      if( pgmData[10] )
         {
         WinCheckButton(hwndDlg,ID_NOSHOW,1);
         WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFF), TRUE);
         WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFFO), TRUE);
         }
      else
         {
         WinCheckButton(hwndDlg, ID_NOSHOW,0);
         WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFF), FALSE);
         WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFFO), FALSE);
         }   
      }
      break;

   case WM_CONTROL:
      switch (SHORT1FROMMP(mp1))
         {
         case ID_USASTYLE:
            if (HIUSHORT(mp1) == BN_CLICKED)
               {
               if( WinQueryButtonCheckstate(hwndDlg, ID_USASTYLE) )
                  {
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE,0);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE2,0);
                  }
               else   
                  {
                  WinCheckButton(hwndDlg, ID_USASTYLE,1);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE,0);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE2,0);
                  }
               }
            return(MRESULT)TRUE;
            
         case ID_EUROPEANSTYLE:
               {
               if( WinQueryButtonCheckstate(hwndDlg, ID_EUROPEANSTYLE) )
                  {
                  WinCheckButton(hwndDlg, ID_USASTYLE,0);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE2,0);
                  }
               else   
                  {
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE,1);
                  WinCheckButton(hwndDlg, ID_USASTYLE,0);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE2,0);
                  }
               }
            return(MRESULT)TRUE;
            
         case ID_EUROPEANSTYLE2:
               {
               if( WinQueryButtonCheckstate(hwndDlg, ID_EUROPEANSTYLE2) )
                  {
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE,0);
                  WinCheckButton(hwndDlg, ID_USASTYLE,0);
                  }
               else   
                  {
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE2,1);
                  WinCheckButton(hwndDlg, ID_EUROPEANSTYLE,0);
                  WinCheckButton(hwndDlg, ID_USASTYLE,0);
                  }
               }
            return(MRESULT)TRUE;
            
         case ID_DISABLEALL:
            if (HIUSHORT(mp1) == BN_CLICKED)
               {
               if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLEALL) )
                  {
                  WinCheckButton(hwndDlg,ID_DISABLEALL,FALSE);
                  pgmData[0] = 0;
                  }
               else   
                  {
                  WinCheckButton(hwndDlg,ID_DISABLEALL,TRUE);
                  pgmData[0] = 1;
                  }
               if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLEALL) )
                  {
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFOLDTREEP), FALSE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFILEP), FALSE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLETB), FALSE);
                  }
               else
                  {
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFOLDTREEP), TRUE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLEFILEP), TRUE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_DISABLETB), TRUE);
                  }
               }
            return(MRESULT)TRUE;
               
         case ID_NOSHOW:
            if (HIUSHORT(mp1) == BN_CLICKED)
               {
               if( WinQueryButtonCheckstate(hwndDlg, ID_NOSHOW) )
                  {
                  WinCheckButton(hwndDlg,ID_NOSHOW,FALSE);
                  pgmData[10] = 0;
                  }
               else   
                  {
                  WinCheckButton(hwndDlg,ID_NOSHOW,TRUE);
                  pgmData[10] = 1;
                  }
               if( !WinQueryButtonCheckstate(hwndDlg, ID_NOSHOW) )
                  {
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFF), FALSE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFFO), FALSE);
                  }
               else
                  {
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFF), TRUE);
                  WinEnableWindow(WinWindowFromID(hwndDlg, ID_NOSHOWFFO), TRUE);
                  }
               }
            return(MRESULT)TRUE;
               
         }
         break;
   
   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
         {
         case ID_STATSOK:
            {
            if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLEALL) )
               pgmData[0] = 1;
            else
               pgmData[0] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLEFOLDTREEP) )
               pgmData[1] = 1;
            else
               pgmData[1] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLEFILEP) )
               pgmData[2] = 1;
            else
               pgmData[2] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_DISABLETB) )
               pgmData[3] = 1;
            else
               pgmData[3] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_SHOWFILES) )
               pgmData[4] = 1;
            else
               pgmData[4] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_SHOWBYTES) )
               pgmData[5] = 1;
            else
               pgmData[5] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_SHOWDIRS) )
               pgmData[6] = 1;
            else
               pgmData[6] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_SHOWOBJS) )
               pgmData[7] = 1;
            else
               pgmData[7] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_SHOWPATH) )
               pgmData[8] = 1;
            else
               pgmData[8] = 0;   
            
            if( WinQueryButtonCheckstate(hwndDlg, ID_USASTYLE) )
               pgmData[9] = 0;

            if( WinQueryButtonCheckstate(hwndDlg, ID_EUROPEANSTYLE) )
               pgmData[9] = 1;

            if( WinQueryButtonCheckstate(hwndDlg, ID_EUROPEANSTYLE2) )
               pgmData[9] = 2;

            if( WinQueryButtonCheckstate(hwndDlg, ID_NOSHOW) )
               pgmData[10] = 1;
            else
               pgmData[10] = 0;
                    
            if( WinQueryButtonCheckstate(hwndDlg, ID_NOSHOWFF) )
               pgmData[11] = 1;
               
            if( WinQueryButtonCheckstate(hwndDlg, ID_NOSHOWFFO) )
               pgmData[11] = 2;
                    
            WinQueryDlgItemText(hwndDlg, ID_STATSREGENTRY, sizeof(SCODE), SCODE);
            
            PrfWriteProfileString(HINI_USERPROFILE, "StatsIsInstalled", "rc", SCODE);  
            saveSet();
            querySet();
            WinDismissDlg(hwndDlg, FALSE);
            }
            break;

         default :
            return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
         }
      break;

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}






BOOL setConMenu( HWND hmenu, USHORT msg)
{
    MENUITEM mi ;
    ULONG ulStyle ;

    WinSendMsg( hmenu, MM_QUERYITEM, MPFROM2SHORT( msg, TRUE), MPFROMP( &mi)) ;

    if( !mi.hwndSubMenu)
        return FALSE ;

    ulStyle = WinQueryWindowULong( mi.hwndSubMenu, QWL_STYLE) ;
    if( WinSetWindowULong( mi.hwndSubMenu, QWL_STYLE, ulStyle | MS_CONDITIONALCASCADE))
        return TRUE ;
    return FALSE ;
}






VOID _Optlink showTreeStats(PVOID n)
{
HAB habT;
HMQ hmqT;
INT i, k, a, sslen;
INT nf;
CHAR nfstr[10];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStrTF[GLMAXPATH];
CHAR msgStrB[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
ULONG sssize = sizeof(searchStr);
ULONG totB;
div_t dvt;
HWND hwndF;
DLGDATAFOLD dlgdat;
CHAR ndstr[40];
CHAR ndTmpStr[40];
SOMAny *sSelf;
PSZ ftitle;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

sSelf = (SOMAny *)n;
_wpQueryRealName(sSelf, searchStr, &sssize, TRUE);

if( strlen(searchStr) == 2 && searchStr[1] == ':' )
   strcat(searchStr, "\\");
   
if( !TSBUSY )
   {
   TSBUSY = TRUE;
   ftitle = _wpQueryTitle(sSelf);
   totB = 0;
   totFiles = 0;
   totFS = 0;
   bytesTotF = 0;
   strcpy(msgStrTF, "");
   strcpy(msgStrB, "");
   TOTDIRS = 0;
   totB = findDirList(searchStr);
   itoa(TOTDIRS, ndTmpStr, 10);
   nf = searchP(searchStr);
   totFiles += nf;
   totB += totFS;
   itoa(totFiles, nfTmpStr, 10);
   ltoa(totB, tmpNumStr, 10);

   strcpy(nfstr, nfTmpStr);
   strcpy(totFSStr, tmpNumStr);
   addComa(nfstr);
   addComa(totFSStr);
   
   strcat(msgStrTF, nfstr);
   strcat(msgStrB, totFSStr);

   strcpy(ndstr, "");
   strcat(ndstr, ndTmpStr);
   addComa(ndstr);

   strcpy(dlgdat.title, ftitle);
   strcpy(dlgdat.fnameStr, searchStr);
   strcpy(dlgdat.dirStr, ndstr);
   strcpy(dlgdat.fsizeStr, msgStrTF);
   strcpy(dlgdat.ftimeStr, msgStrB);
   strcpy(dlgdat.fdateStr, "Tree stats");
   hwndF = WinLoadDlg(HWND_DESKTOP,
                      HWND_DESKTOP,
                      statsProcP,
                      hResource,
                      ID_DLG_STATSF,
                      (PVOID)&dlgdat);
   if( hwndF == NULLHANDLE )
      TSBUSY = FALSE;
   WinProcessDlg(hwndF);
   }
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






MRESULT EXPENTRY statsProcP(HWND hwndDlg, ULONG msg,
                                             MPARAM mp1, MPARAM mp2 )
{

switch ( msg )
   {
   case WM_INITDLG:
      {
      DLGDATAFOLD *dlgS;
      POINTL mptl;
      LONG offx, offy, xx, yy;
      INT b, q;
      SWP swp;
      CHAR fdName[GLMAXPATH];

      offx = 0;
      offy = 0;
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);  
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-80)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-80)+5) - dtWidth;
         }
      if( (mptl.x-(80+5)) < 0 )
         {
         offx = (mptl.x-(80+5)) ;
         }
      if( (mptl.y+(swp.cy-45)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(45+5)) < 0 )
         {
         offy = (mptl.y-(45+5));
         }

      xx = (mptl.x - 80) - offx;
      yy = (mptl.y - 45) - offy;
      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );

      dlgS = (DLGDATAFOLD *)mp2;

      WinSetWindowText(WinWindowFromID(hwndDlg, FID_TITLEBAR), dlgS->title);

      WinSendDlgItemMsg(hwndDlg, ID_DLG_TEXT,EM_SETTEXTLIMIT,
                        MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT), dlgS->fnameStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT2), dlgS->fdateStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DIRCOUNT), "Total folders");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT3), "Total files");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT4), "Total bytes");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DIRCOUNTNUM), dlgS->dirStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT3NUM), dlgS->fsizeStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT4NUM), dlgS->ftimeStr);
      
      TSBUSY = FALSE;
      }
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
        {
        case DID_CANCEL:
           WinDismissDlg(hwndDlg, FALSE);
           break;
        }
      break;

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}





VOID _Optlink showFolderStats(PVOID n)
{
HAB habT;
HMQ hmqT;
INT i, k, a, sslen;
INT nf, nd;
CHAR nfstr[10];
CHAR ndstr[40];
CHAR ndTmpStr[40];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStrTF[GLMAXPATH];
CHAR msgStrB[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
ULONG sssize = sizeof(searchStr);
div_t dvt;
HWND hwndF;
DLGDATAFOLD dlgdataf;
SOMAny *sSelf;
PSZ ftitle;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

sSelf = (SOMAny *)n;
_wpQueryRealName(sSelf, searchStr, &sssize, TRUE);

if( strlen(searchStr) == 2 && searchStr[1] == ':' )
   strcat(searchStr, "\\");

if( !SBUSY )
   {
   SBUSY = TRUE;
   nd = 0;
   ftitle = _wpQueryTitle(sSelf);
   totFS = 0;
   strcpy(tmpNumStr, "");
   strcpy(totFSStr, "");
   strcpy(msgStrTF, "");
   strcpy(msgStrB, "");
   nf = searchP(searchStr);
   itoa(nf, nfstr, 10);
   ltoa(totFS, totFSStr, 10);
   nd = searchPDirs(searchStr);
   itoa(nd, ndTmpStr, 10);

   addComa(nfstr);
   addComa(totFSStr);

   strcpy(ndstr, "");
   strcat(ndstr, ndTmpStr);
   addComa(ndstr);

   strcat(msgStrTF, nfstr);
   strcat(msgStrB, totFSStr);
   strcpy(dlgdataf.title, ftitle);
   strcpy(dlgdataf.dirStr, ndstr);
   strcpy(dlgdataf.fnameStr, searchStr);
   strcpy(dlgdataf.fsizeStr, msgStrTF);
   strcpy(dlgdataf.ftimeStr, msgStrB);
   strcpy(dlgdataf.fdateStr, "folder stats");

   hwndF = WinLoadDlg(HWND_DESKTOP,
                                 HWND_DESKTOP,
                                 statsProcF,
                                 hResource,
                                 ID_DLG_STATSF,
                                 (PVOID)&dlgdataf);
   if( hwndF == NULLHANDLE )                              
      SBUSY = FALSE; 
   WinProcessDlg(hwndF);
   }
   
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






MRESULT EXPENTRY statsProcF(HWND hwndDlg, ULONG msg,
                           MPARAM mp1, MPARAM mp2 )
{
switch ( msg )
   {
   case WM_INITDLG:
      {
      DLGDATAFOLD *dlgS;
      POINTL mptl;
      LONG offx, offy, xx, yy;
      INT b, q;
      SWP swp;
      CHAR fdName[GLMAXPATH];

       
       
      offx = 0;
      offy = 0;
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);  
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-80)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-80)+5) - dtWidth;
         }
      if( (mptl.x-(80+5)) < 0 )
         {
         offx = (mptl.x-(80+5)) ;
         }
      if( (mptl.y+(swp.cy-45)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(45+5)) < 0 )
         {
         offy = (mptl.y-(45+5));
         }

      xx = (mptl.x - 80) - offx;
      yy = (mptl.y - 45) - offy;
      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );

      dlgS = (DLGDATAFOLD *)mp2;

       
      WinSetWindowText(WinWindowFromID(hwndDlg, FID_TITLEBAR), dlgS->title);

      WinSendDlgItemMsg(hwndDlg, ID_DLG_TEXT,EM_SETTEXTLIMIT,
                        MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT), dlgS->fnameStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT2), dlgS->fdateStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DIRCOUNT), "Total folders");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT3), "Total files");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT4), "Total bytes");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DIRCOUNTNUM), dlgS->dirStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT3NUM), dlgS->fsizeStr);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_FDTEXT4NUM), dlgS->ftimeStr);
      SBUSY = FALSE;  
      
      }
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
        {
        case DID_CANCEL:
           WinDismissDlg(hwndDlg, FALSE);
           break;
        }
      break;

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}






VOID _Optlink showFileStats(PVOID n)
{
HAB habT;
HMQ hmqT;
SOMAny *sSelf;
CHAR fsStr[GLMAXPATH];
CHAR nzstr[GLMAXPATH];
CHAR fsizeStr[24];
CHAR eaTmpStr[24];
CHAR rPath[GLMAXPATH];
ULONG rsize = sizeof(rPath);
FILESTATUS3  fsts3ConfigInfo = {{0}};
ULONG        ulBufSize     = sizeof(FILESTATUS3);
HFILE        hfConfig      = 0;
ULONG        ulOpenAction  = 0;
APIRET       rc            = NO_ERROR;
FDATE fd;
FTIME ft;
CHAR *p;
CHAR createdate[9];
CHAR createdatelc[9];
CHAR createdatela[9];
CHAR createtime[7];
CHAR numbuf[35];
CHAR suffix[6];
HWND hwndD;
INT i, k, a, sslen, j;
div_t dvt;
ULONG attrRC, origattr, easize;
PSZ ftitle;



habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


sSelf = (SOMAny *)n;

// pgmData[31] = 0;    CHANGE THIS EVENTUALLY!

_wpRefresh(sSelf, 0, 0);
_wpQueryRealName(sSelf, rPath, &rsize, TRUE);
ftitle = _wpQueryTitle(sSelf);
strcpy(dlgdat.title, ftitle);
strcpy(dlgdat.fnameStr, rPath);

rc = DosOpen(rPath,
                &hfConfig,
                &ulOpenAction,
                0L,0L,
                OPEN_ACTION_FAIL_IF_NEW |
                OPEN_ACTION_OPEN_IF_EXISTS,
                OPEN_FLAGS_NOINHERIT | OPEN_ACCESS_READONLY |
                OPEN_SHARE_DENYNONE,
                0L);

if (rc != NO_ERROR)
   {
   WinDestroyMsgQueue(hmqT);
   WinTerminate(habT);
   _endthread();
   return;
   }

DosQueryFileInfo(hfConfig,
                       FIL_STANDARD,
                       &fsts3ConfigInfo,
                       ulBufSize);

rc = DosClose(hfConfig);

ltoa(fsts3ConfigInfo.cbFile, fsizeStr, 10);


sslen = strlen(fsizeStr);

addComa(fsizeStr);

strcpy(fsStr, "");
strcat(fsStr, fsizeStr);
strcpy(dlgdat.fsizeStr, fsStr);

for( j=0;j<3;j++ )
   {
   switch(j)
      {
      case 0:
         _wpQueryCreation(sSelf, &fd, &ft);
         strcpy(fsStr, "");    // time stamp
         break;

      case 1:
         _wpQueryLastAccess(sSelf, &fd, &ft);
         strcpy(fsStr, "");    // time stamp
         break;

      case 2:
         _wpQueryLastWrite(sSelf, &fd, &ft);
         strcpy(fsStr, "");    // time stamp
         break;
      }

   switch(pgmData[9])
      {
      case 0:
         {
         if( ft.hours > 12 )
            {
            strcpy(suffix, " p.m.");
            p = _itoa(ft.hours-12, numbuf, 10);
            }
         else
            {
            strcpy(suffix, " a.m.");
            p = _itoa(ft.hours, numbuf, 10);
            }
         if( ft.hours == 0 )
            {
            strcpy(createtime, "12");
            }
         else
            strcpy(createtime, p);
         strcat(createtime, ":");
         p = _itoa(ft.minutes, numbuf, 10);
         if( ft.minutes < 10 )
            {
            strcat(createtime, "0");
            strcat(createtime, p);
            }
         else
            strcat(createtime, p);
         strcat(createtime, suffix);
         sprintf(numbuf, "%6s", createtime);
         strcat(fsStr, createtime);
         }
         break;
         
      case 1:   
         {
         if( ft.hours < 10 )
            {
            if( ft.minutes < 10 )
               sprintf(createtime, "0%i:0%i", ft.hours, ft.minutes);
            else
               sprintf(createtime, "0%i:%i", ft.hours, ft.minutes);
            }
         else
            {
            if( ft.minutes < 10 )
               sprintf(createtime, "%i:0%i", ft.hours, ft.minutes);
            else
               sprintf(createtime, "%i:%i", ft.hours, ft.minutes);
            }
         strcat(fsStr, createtime);
         }
         break;
         
      case 2:
         {
         if( ft.hours < 10 )
            {
            if( ft.minutes < 10 )
               sprintf(createtime, "0%i:0%i", ft.hours, ft.minutes);
            else
               sprintf(createtime, "0%i:%i", ft.hours, ft.minutes);
            }
         else
            {
            if( ft.minutes < 10 )
               sprintf(createtime, "%i:0%i", ft.hours, ft.minutes);
            else
               sprintf(createtime, "%i:%i", ft.hours, ft.minutes);
            }
         strcat(fsStr, createtime);
         }
         break;
      }      


   switch(j)
      {
      case 0:
         strcpy(dlgdat.ftimeStr, fsStr);
         break;

      case 1:
         strcpy(dlgdat.ftimeStrLA, fsStr);
         break;

      case 2:
         strcpy(dlgdat.ftimeStrLC, fsStr);
         break;
      }


   switch(j)
      {
      case 0:
         strcpy(fsStr, "");     // date stamp
         break;

      case 1:
         strcpy(fsStr, "");     // date stamp
         break;

      case 2:
         strcpy(fsStr, "");     // date stamp
         break;
      }
   
   
   switch(pgmData[9])
      {
      case 0:
         {
         p = _itoa(fd.month, numbuf, 10);
         strcpy(createdate, p);
         strcat(createdate, "/");
         p = _itoa(fd.day, numbuf, 10);
         if( fd.day < 10 )
            {
            strcat(createdate, "0");
            strcat(createdate, p);
            strcat(createdate, "/");
            }
         else
            {
            strcat(createdate, p);
            strcat(createdate, "/");
            }
         p = _itoa(fd.year+80, numbuf, 10);
         strcat(createdate, p);
         sprintf(numbuf, "%8s", createdate);
         strcat(fsStr, createdate);
         }
         break;
         
      case 1:
         {
         if( fd.day < 10 )
            {
            if( fd.month < 10 )
               sprintf(createdate, "0%i/0%i/%i", fd.day, fd.month, 80+fd.year);
            else
               sprintf(createdate, "0%i/%i/%i", fd.day, fd.month, 80+fd.year);
            }
         else
            {
            if( fd.month < 10 )
               sprintf(createdate, "%i/0%i/%i", fd.day, fd.month, 80+fd.year);
            else
               sprintf(createdate, "%i/%i/%i", fd.day, fd.month, 80+fd.year);
            }
         strcat(fsStr, createdate);
         }
         break;
         
      case 2:
         if( fd.day < 10 )
            {
            if( fd.month < 10 )
               sprintf(createdate, "%i/0%i/0%i", 80+fd.year, fd.month, fd.day);
            else
               sprintf(createdate, "%i/%i/0%i", 80+fd.year, fd.month, fd.day);
            }
         else
            {
            if( fd.month < 10 )
               sprintf(createdate, "%i/0%i/%i", 80+fd.year, fd.month, fd.day);
            else
               sprintf(createdate, "%i/%i/%i", 80+fd.year, fd.month, fd.day);
            }
         strcat(fsStr, createdate);
         break;
      }   
      
   switch(j)
      {
      case 0:
         strcpy(dlgdat.fdateStr, fsStr);
         break;

      case 1:
         strcpy(dlgdat.fdateStrLA, fsStr);
         break;

      case 2:
         strcpy(dlgdat.fdateStrLC, fsStr);
         break;
      }
   }

easize = _wpQueryEASize(sSelf); // extended attributes size
ltoa(easize, eaTmpStr, 10);
strcpy(dlgdat.eaStr, "");
strcat(dlgdat.eaStr, eaTmpStr);

dlgdat.attrF = _wpQueryAttr(sSelf); // file attributes
origattr = dlgdat.attrF;


hwndD = WinLoadDlg(HWND_DESKTOP,
                             HWND_DESKTOP,
                             fileStatsProc,
                             hResource,
                             ID_DLG_STATS,
                             0);

WinProcessDlg(hwndD);

if( dlgdat.attrF != origattr )
   { 
   _wpSetAttr(sSelf, dlgdat.attrF);
   _wpRefresh(sSelf, 0, 0);
   }


WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






MRESULT EXPENTRY fileStatsProc(HWND hwndDlg, ULONG msg,
                                                MPARAM mp1, MPARAM mp2 )
{
CHAR fata[4];
CHAR fath[4];
CHAR fatr[4];
CHAR fats[4];

switch ( msg )
   {
   case WM_INITDLG:
      {
      ULONG newFattra;
      ULONG newFattrh;
      ULONG newFattrr;
      ULONG newFattrs;
      ULONG NewFattr;
      POINTL mptl;
      LONG offx, offy, xx, yy;
      SWP swp;
      INT i, k;
      CHAR tbString[GLMAXPATH];


      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);  
      newFattra = 0;
      newFattrh = 0;
      newFattrr = 0;
      newFattrs = 0;
      offx = 0;
      offy = 0;
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);
      if( (mptl.x+(swp.cx-80)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-80)+5) - dtWidth;
         }
      if( (mptl.x-(80+5)) < 0 )
         {
         offx = (mptl.x-(80+5)) ;
         }
      if( (mptl.y+(swp.cy-30)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(30+5)) < 0 )
         {
         offy = (mptl.y-(30+5));
         }
      xx = (mptl.x - 80)-offx;
      yy = (mptl.y - 30)-offy;
      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );

      WinSetWindowText(WinWindowFromID(hwndDlg, FID_TITLEBAR), dlgdat.title);

      WinSendDlgItemMsg(hwndDlg, ID_DLG_TEXT,EM_SETTEXTLIMIT,
                        MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT), dlgdat.fnameStr);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT2), "File size");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT2NUM), dlgdat.fsizeStr);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_EASIZE), "EA size");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_EASIZENUM), dlgdat.eaStr);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT4), "Create date");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT4NUM), dlgdat.fdateStr);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT3), "Create time");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_DLG_TEXT3NUM), dlgdat.ftimeStr);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LCDATE), "Last write date");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LCDATENUM), dlgdat.fdateStrLC);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LCTIME), "Last write time");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LCTIMENUM), dlgdat.ftimeStrLC);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LADATE), "Last access date");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LADATENUM), dlgdat.fdateStrLA);

      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LATIME), "Last access time");
      WinSetWindowText(WinWindowFromID(hwndDlg, ID_LATIMENUM), dlgdat.ftimeStrLA);
      
      switch(dlgdat.attrF)
         {
         case 0x000:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x001:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x002:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x003:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x004:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x005:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x006:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x007:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x020:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x021:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x022:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x023:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;

         case 0x024:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x025:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x026:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         case 0x027:
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
            break;

         default :
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
            WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
            break;
         }
      }
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
        {
        case DID_CANCEL:
           {
           ULONG newFattra;
           ULONG newFattrh;
           ULONG newFattrr;
           ULONG newFattrs;
           ULONG NewFattr;


           WinQueryDlgItemText(hwndDlg,
                               ID_FATA,
                               sizeof(fata),
                               fata);
           if( stricmp(fata, "A+") == 0 )
              newFattra = 0x020;
           else
              newFattra = 0x000;

           WinQueryDlgItemText(hwndDlg,
                               ID_FATH,
                               sizeof(fath),
                               fath);
           if( stricmp(fath, "H+") == 0 )
              newFattrh = 0x002;
           else
              newFattrh = 0x000;

           WinQueryDlgItemText(hwndDlg,
                               ID_FATR,
                               sizeof(fatr),
                               fatr);
           if( stricmp(fatr, "R+") == 0 )
              newFattrr = 0x001;
           else
              newFattrr = 0x000;

           WinQueryDlgItemText(hwndDlg,
                               ID_FATS,
                               sizeof(fats),
                               fats);
           if( stricmp(fats, "S+") == 0 )
              newFattrs = 0x004;
           else
              newFattrs = 0x000;

           NewFattr = newFattra | newFattrh | newFattrr | newFattrs;
           dlgdat.attrF = 0x000;
           dlgdat.attrF = NewFattr;
           WinDestroyWindow(hwndDlg);
           }
           break;

        case ID_FATA:
           WinQueryDlgItemText(hwndDlg,
                               ID_FATA,
                               sizeof(fata),
                               fata);
           if( stricmp(fata, "A+") == 0 )
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A-");
              }
           else
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATA), "A+");
              }
           break;

        case ID_FATH:
           WinQueryDlgItemText(hwndDlg,
                               ID_FATH,
                               sizeof(fath),
                               fath);
           if( stricmp(fath, "H+") == 0 )
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H-");
              }
           else
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATH), "H+");
              }
           break;

        case ID_FATR:
           WinQueryDlgItemText(hwndDlg,
                               ID_FATR,
                               sizeof(fatr),
                               fatr);
           if( stricmp(fatr, "R+") == 0 )
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R-");
              }
           else
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATR), "R+");
              }
           break;

        case ID_FATS:
           WinQueryDlgItemText(hwndDlg,
                               ID_FATS,
                               sizeof(fats),
                               fats);
           if( stricmp(fats, "S+") == 0 )
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S-");
              }
           else
              {
              WinSetWindowText(WinWindowFromID(hwndDlg, ID_FATS), "S+");
              }
           break;
        }
      break;

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}






INT addComa(CHAR *numstr)
{
INT sslen;
CHAR nzstr[GLMAXPATH];


sslen = strlen(numstr);

if( sslen > 3 )
   {
   strcpy(nzstr, numstr);
   
   switch( sslen )
      {
      case 4:
      case 5:
      case 6:
         strinsert(nzstr+(sslen-3), ',');
         break;



      case 7:
      case 8:
      case 9:
         strinsert(nzstr+(sslen-6), ',');
         strinsert(nzstr+(sslen-2), ',');
         break;



      case 10:
      case 11:
      case 12:
         strinsert(nzstr+(sslen-9), ',');
         strinsert(nzstr+(sslen-5), ',');
         strinsert(nzstr+(sslen-1), ',');
         break;



      case 13:
      case 14:
      case 15:
         strinsert(nzstr+(sslen-12), ',');
         strinsert(nzstr+(sslen-8), ',');
         strinsert(nzstr+(sslen-4), ',');
         strinsert(nzstr+(sslen-0), ',');
         break;



      case 16:
      case 17:
      case 18:
         strinsert(nzstr+(sslen-15), ',');
         strinsert(nzstr+(sslen-11), ',');
         strinsert(nzstr+(sslen-7), ',');
         strinsert(nzstr+(sslen-3), ',');
         strinsert(nzstr+(sslen+1), ',');
         break;



      case 19:
      case 20:
      case 21:
         strinsert(nzstr+(sslen-18), ',');
         strinsert(nzstr+(sslen-14), ',');
         strinsert(nzstr+(sslen-10), ',');
         strinsert(nzstr+(sslen-6), ',');
         strinsert(nzstr+(sslen-2), ',');
         strinsert(nzstr+(sslen+2), ',');
         break;



      case 22:
      case 23:
      case 24:
         strinsert(nzstr+(sslen-21), ',');
         strinsert(nzstr+(sslen-17), ',');
         strinsert(nzstr+(sslen-13), ',');
         strinsert(nzstr+(sslen-9), ',');
         strinsert(nzstr+(sslen-5), ',');
         strinsert(nzstr+(sslen-1), ',');
         strinsert(nzstr+(sslen+3), ',');
         break;



      case 25:
      case 26:
      case 27:
         strinsert(nzstr+(sslen-24), ',');
         strinsert(nzstr+(sslen-20), ',');
         strinsert(nzstr+(sslen-16), ',');
         strinsert(nzstr+(sslen-12), ',');
         strinsert(nzstr+(sslen-8), ',');
         strinsert(nzstr+(sslen-4), ',');
         strinsert(nzstr+(sslen-0), ',');
         strinsert(nzstr+(sslen+4), ',');
         break;

      default :
         break;
      }

   strcpy(numstr, nzstr);
   }
return(1);
}





INT isOpenFold(stats *somSelf)
{
WPFolder *Folder, *NextFolder;
INT ret;

ret = 0;
Folder = _wpclsQueryOpenFolders(_WPFolder, NULL, QC_FIRST, FALSE);
while( Folder )
   {
   if( Folder == somSelf )
      ret = 1;
   NextFolder = _wpclsQueryOpenFolders(_WPFolder, NULL, QC_NEXT, FALSE);
   Folder = NextFolder;
   }

return(ret);
}





VOID _Optlink addNotify(PVOID n)
{
HAB habT;
HMQ hmqT;
SOMAny *sSelf;
PVIEWITEM pcurt;
PUSEITEM puse;
CHAR foln[GLMAXPATH];
ULONG folnsize = sizeof(foln);
BOOL ISRFOLD;
PVIEWITEM pany;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


sSelf = (SOMAny *)n;
ISRFOLD = FALSE;
DosSleep(500);

if( sSelf != NULL  &&  _wpIsObjectInitialized(sSelf) )
   {
   if( !_somIsA(sSelf, _WPDesktop) )
      {
      if( _wpQueryRealName(sSelf, foln, &folnsize, TRUE) == FALSE )
         {
         WAITAHOTSECADD = FALSE;
         return;
         }
   
      if( strlen(foln) < 3 && foln[1] == ':' )
         {
         ISRFOLD = TRUE;
         }
      
      if(  _wpIsObjectInitialized(sSelf) )
         {
         pcurt = _wpFindViewItem(sSelf, VIEW_CONTENTS, NULL);
         if( pcurt )
            {
            if( ISRFOLD )
               {
               if( DISKSREADY )
                  {
                  ULONG oattr;
            
            
                  oattr = _wpQueryFldrAttr(sSelf, OPEN_CONTENTS);
                  if( oattr & CV_ICON ) 
                     setFolderStatsRD(sSelf, pcurt->handle); 
                  } 
               }
            else
               {   
               ULONG oattr;
            
            
               oattr = _wpQueryFldrAttr(sSelf, OPEN_CONTENTS);
               if( oattr & CV_ICON ) 
                  setFolderStats(sSelf, pcurt->handle);
               }
            }   
         }
      }
   }   

WAITAHOTSECADD = FALSE;
 
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





VOID _Optlink deleteNotify(PVOID n)
{
HAB habT;
HMQ hmqT;
SOMAny *sSelf;
BOOL FOUND;
PVIEWITEM pcurt;
CHAR foln[GLMAXPATH];
ULONG folnsize = sizeof(foln);
BOOL ISRFOLD;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

DosSleep(500);
sSelf = (SOMAny *)n;
ISRFOLD = FALSE;

if( sSelf != NULL &&  _wpIsObjectInitialized(sSelf) )
   {
   if( !_somIsA(sSelf, _WPDesktop) )
      { 
      if( _wpQueryRealName(sSelf, foln, &folnsize, TRUE) == FALSE )
         {
         WAITAHOTSECDEL = FALSE;
         return;
         }

      if( strlen(foln) < 3 && foln[1] == ':' )
         {
         ISRFOLD = TRUE;
         }

      if(  _wpIsObjectInitialized(sSelf) )
         {
         pcurt = _wpFindViewItem(sSelf, VIEW_CONTENTS, NULL);
         if( pcurt )
            {
            if( ISRFOLD )
               {
               if( DISKSREADY )
                  {
                  ULONG oattr;
            
                  oattr = _wpQueryFldrAttr(sSelf, OPEN_CONTENTS);
                  if( oattr & CV_ICON ) 
                     {
                     setFolderStatsRD(sSelf, pcurt->handle);
                     }
                  } 
               }
            else
               {   
               ULONG oattr;
            
               oattr = _wpQueryFldrAttr(sSelf, OPEN_CONTENTS);
               if( oattr & CV_ICON ) 
                  {
                  setFolderStats(sSelf, pcurt->handle);
                  }
               }
            }   
         }
      }
   }   

WAITAHOTSECDEL = FALSE;
 
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





INT getObjCount(SOMAny *sSelf, CHAR *dTopFold)
{
INT nobj;
SOMAny *Object, *NextObject;


if( !sSelf )
   return(0);
nobj = 0;
if( _wpPopulate(sSelf, NULLHANDLE, NULL, FALSE) )
   {
   Object = _wpQueryContent(sSelf, NULL, QC_FIRST);
   while(Object && sSelf)
      {
      nobj++;
      NextObject = _wpQueryContent(sSelf, Object, QC_NEXT);
      _wpUnlockObject(Object);
      Object = NextObject;
      }
   return(nobj);   
   }
return(-1);   
}






VOID setFolderStats(SOMAny *sSelf, HWND hwndF)
{
INT i, k, a, sslen, lastS, ix;
INT nf;
CHAR nfstr[10];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStr[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
CHAR tStr[GLMAXPATH];
CHAR hdrStr[GLMAXPATH];
div_t dvt;
CHAR ndTmpStr[40];
INT nd;
CHAR dTopFold[GLMAXPATH];
ULONG cfsize = sizeof(dTopFold);
CHAR foldtitle[GLMAXPATH];
PSZ ft;
CHAR totobjstr[24];
INT totobj;



if( !sSelf )
   return;
   
ft = _wpQueryTitle(sSelf);
strcpy(foldtitle, ft);

if( !_wpQueryRealName(sSelf, dTopFold, &cfsize, TRUE) )
   return;

STATSBUSY = TRUE;
if( hwndF != NULLHANDLE )
   {
   if( strlen(dTopFold) <= 3 )
      {
      if( strlen(dTopFold) < 2 )
         {
         STATSBUSY = TRUE;
         return;
         }
      if( dTopFold[strlen(dTopFold)-1] != '\\' )
         {
         strcpy(tStr, dTopFold);
         strcat(tStr, "\\");
         }
      else
         strcpy(tStr, dTopFold);
      }
   else
      {
      for( ix=0;ix<strlen(dTopFold);ix++ )
         {
         if( dTopFold[ix] == '\\' )
            lastS = ix;
         }
      strncpy(tStr, dTopFold+(lastS+1), strlen(dTopFold)-(lastS));
      tStr[strlen(dTopFold)-(lastS)] = '\0';
      }

   strcpy(searchStr, dTopFold );
   totFS = 0;
   strcpy(tmpNumStr, "");
   strcpy(totFSStr, "");
   nf = searchP(searchStr);
   itoa(nf, nfTmpStr, 10);
   ltoa(totFS, tmpNumStr, 10);

   // GET NUMBER OF SUB DIRECTORIES
   nd = searchPDirs(searchStr);
   itoa(nd, ndTmpStr, 10);

   strcpy(nfstr, nfTmpStr);
   strcpy(totFSStr, tmpNumStr);
   addComa(nfstr);
   addComa(totFSStr);

   totobj = getObjCount(sSelf, dTopFold);
   if( totobj == -1 )
      return;
   itoa(totobj, totobjstr, 10);

   strcpy(msgStr, foldtitle);
   if( (pgmData[10] == 1 && pgmData[11] == 1 && nd == 0 && nf == 0) ||
       (pgmData[10] == 1 && pgmData[11] == 2 && nd == 0 && nf == 0 && totobj == 0) )
      {
      }
   else
      {   
      if( pgmData[4] == 1 )
         {
         // FILES
         strcat(msgStr, " - ");
         strcat(msgStr, "files: ");
         strcat(msgStr, nfstr);
         }
      if( pgmData[5] == 1 )
         {
         // BYTES
         strcat(msgStr, " - ");
         strcat(msgStr, "bytes: ");
         strcat(msgStr, totFSStr);
         }

      if( pgmData[6] == 1 )
         {
         // DIRECTORIES
         strcat(msgStr, " - ");
         strcat(msgStr, "dirs: ");
         strcat(msgStr, ndTmpStr);
         }
         
      if( pgmData[7] == 1 )
         {
         // OBJECTS
         strcat(msgStr, " - ");
         strcat(msgStr, "objs: ");
         strcat(msgStr, totobjstr);
         }
         
      if( pgmData[8] == 1 )
         {
         // PATH
         strcat(msgStr, " - ");
         strcat(msgStr, "[");
         strcat(msgStr, dTopFold);
         strcat(msgStr, "]");
         }
      }   
      
   strcpy(hdrStr, "Folder stats : ");
   strcat(hdrStr, searchStr);

   if( hwndF )
      WinSetWindowText(WinWindowFromID(hwndF, FID_TITLEBAR), msgStr);
   }
else
   {
   // debugMsgStr("Got this far!", "NULL handle");
   }
   
STATSBUSY = FALSE;
}





VOID setFolderStatsRD(SOMAny *sSelf, HWND hwndF)
{
INT i, k, a, sslen, lastS, ix;
INT nf;
CHAR nfstr[10];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStr[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
CHAR tStr[GLMAXPATH];
CHAR hdrStr[GLMAXPATH+40];
div_t dvt;
CHAR ndTmpStr[40];
INT nd;
CHAR dTopFold[GLMAXPATH];
ULONG cfsize = sizeof(dTopFold);
ULONG drv;
CHAR totobjstr[24];
INT totobj;



if( !sSelf )
   return;
   
if( !_wpQueryRealName(sSelf, dTopFold, &cfsize, TRUE) )
   return;

if( dTopFold[strlen(dTopFold)-1] != '\\' )
   strcat(dTopFold, "\\");

STATSBUSY = 1;
if( hwndF != NULLHANDLE )
   {
   if( strlen(dTopFold) <= 3 )
      {
      if( strlen(dTopFold) < 2 )
         {
         STATSBUSY = 0;
         return;
         }
      if( dTopFold[strlen(dTopFold)-1] != '\\' )
         {
         strcpy(tStr, dTopFold);
         strcat(tStr, "\\");
         }
      else
         strcpy(tStr, dTopFold);
      }
   else
      {
      for( ix=0;ix<strlen(dTopFold);ix++ )
         {
         if( dTopFold[ix] == '\\' )
            lastS = ix;
         }
      strncpy(tStr, dTopFold+(lastS+1), strlen(dTopFold)-(lastS));
      tStr[strlen(dTopFold)-(lastS)] = '\0';
      }

   strcpy(searchStr, dTopFold );
   totFS = 0;
   strcpy(tmpNumStr, "");
   strcpy(totFSStr, "");
   nf = searchP(searchStr);
   itoa(nf, nfTmpStr, 10);
   ltoa(totFS, tmpNumStr, 10);

   // GET NUMBER OF SUB DIRECTORIES
   nd = searchPDirs(searchStr);
   itoa(nd, ndTmpStr, 10);

   strcpy(nfstr, nfTmpStr);
   strcpy(totFSStr, tmpNumStr);
   addComa(nfstr);
   addComa(totFSStr);

   totobj = getObjCount(sSelf, tStr);
   if( totobj == -1 )
      return;
   itoa(totobj, totobjstr, 10);
      
   strcpy(msgStr, tStr);
   if( (pgmData[10] == 1 && pgmData[11] == 1 && nd == 0 && nf == 0) ||
       (pgmData[10] == 1 && pgmData[11] == 2 && nd == 0 && nf == 0 && totobj == 0) )
      {
      }
   else
      {   
      if( pgmData[4] == 1 )
         {
         // FILES
         strcat(msgStr, " - ");
         strcat(msgStr, "files: ");
         strcat(msgStr, nfstr);
         }
      if( pgmData[5] == 1 )
         {
         // BYTES
         strcat(msgStr, " - ");
         strcat(msgStr, "bytes: ");
         strcat(msgStr, totFSStr);
         }
      if( pgmData[6] == 1 )
         {
         // DIRECTORIES
         strcat(msgStr, " - ");
         strcat(msgStr, "dirs: ");
         strcat(msgStr, ndTmpStr);
         }
      if( pgmData[7] == 1 )
         {
         // OBJECTS
         strcat(msgStr, " - ");
         strcat(msgStr, "objs: ");
         strcat(msgStr, totobjstr);
         }
      }
         
   strcpy(hdrStr, "Folder stats : ");
   strcat(hdrStr, searchStr);

   if( hwndF )
      WinSetWindowText(WinWindowFromID(hwndF, FID_TITLEBAR), msgStr);
   }
STATSBUSY = 0;
}





VOID _Optlink setFWinStats(PVOID nfdat)
{
HAB habT;
HMQ hmqT;
INT i, k, a, sslen, lastS, ix;
INT nf;
CHAR nfstr[10];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStr[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
CHAR tStr[GLMAXPATH];
CHAR hdrStr[GLMAXPATH];
div_t dvt;
CHAR ndTmpStr[40];
INT nd;
CHAR dTopFold[GLMAXPATH];
ULONG cfsize = sizeof(dTopFold);
HWND hwndF;
CHAR foldtitle[GLMAXPATH];
WPObject *sSelf;
PSZ ft;
CHAR totobjstr[24];
INT totobj;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


hwndF = (HWND)nfdat;
sSelf = _wpclsQueryObjectFromFrame(_WPDesktop, hwndF);
if( !sSelf )
   return;
   
ft = _wpQueryTitle(sSelf);
strcpy(foldtitle, ft);

if( !_wpQueryRealName(sSelf, dTopFold, &cfsize, TRUE) )
   return;


STATSBUSY = TRUE;
if( hwndF != NULLHANDLE )
   {
   if( strlen(dTopFold) <= 3 )
      {
      if( strlen(dTopFold) < 2 )
         {
         STATSBUSY = TRUE;
         WinDestroyMsgQueue(hmqT);
         WinTerminate(habT);
         _endthread();
         }
      if( dTopFold[strlen(dTopFold)-1] != '\\' )
         {
         strcpy(tStr, dTopFold);
         strcat(tStr, "\\");
         }
      else
         strcpy(tStr, dTopFold);
      }
   else
      {
      for( ix=0;ix<strlen(dTopFold);ix++ )
         {
         if( dTopFold[ix] == '\\' )
            lastS = ix;
         }
      strncpy(tStr, dTopFold+(lastS+1), strlen(dTopFold)-(lastS));
      tStr[strlen(dTopFold)-(lastS)] = '\0';
      }

   strcpy(searchStr, dTopFold );
   totFS = 0;
   strcpy(tmpNumStr, "");
   strcpy(totFSStr, "");
   nf = searchP(searchStr);
   itoa(nf, nfTmpStr, 10);
   ltoa(totFS, tmpNumStr, 10);

   // GET NUMBER OF SUB DIRECTORIES
   nd = searchPDirs(searchStr);
   itoa(nd, ndTmpStr, 10);

   strcpy(nfstr, nfTmpStr);
   strcpy(totFSStr, tmpNumStr);
   addComa(nfstr);
   addComa(totFSStr);

   totobj = getObjCount(sSelf, dTopFold);
   if( totobj == -1 )
      return;
   itoa(totobj, totobjstr, 10);
      
   strcpy(msgStr, foldtitle);
   if( (pgmData[10] == 1 && pgmData[11] == 1 && nd == 0 && nf == 0) ||
       (pgmData[10] == 1 && pgmData[11] == 2 && nd == 0 && nf == 0 && totobj == 0) )
      {
      }
   else
      {   
      if( pgmData[4] == 1 )
         {
         // FILES
         strcat(msgStr, " - ");
         strcat(msgStr, "files: ");
         strcat(msgStr, nfstr);
         }
      if( pgmData[5] == 1 )
         {      
         // BYTES
         strcat(msgStr, " - ");
         strcat(msgStr, "bytes: ");
         strcat(msgStr, totFSStr);
         }

      if( pgmData[6] == 1 )
         {      
         // DIRECTORIES
         strcat(msgStr, " - ");
         strcat(msgStr, "dirs: ");
         strcat(msgStr, ndTmpStr);
         }
      
      if( pgmData[7] == 1 )
         {      
         // OBJECTS
         strcat(msgStr, " - ");
         strcat(msgStr, "objs: ");
         strcat(msgStr, totobjstr);
         }
      
      if( pgmData[8] == 1 )
         {      
         // PATH
         strcat(msgStr, " - ");
         strcat(msgStr, "[");
         strcat(msgStr, dTopFold);
         strcat(msgStr, "]");
         }
      }
              
   strcpy(hdrStr, "Folder stats : ");
   strcat(hdrStr, searchStr);

   if( hwndF )
      WinSetWindowText(WinWindowFromID(hwndF, FID_TITLEBAR), msgStr);
   }
else
   {
   // debugMsgStr("Got this far!", "NULL handle");
   }
   
STATSBUSY = FALSE;


WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}






VOID _Optlink setDiskWinStats(PVOID n)
{
HAB habT;
HMQ hmqT;
INT i, k, a, sslen, lastS, ix;
INT nf;
CHAR nfstr[10];
CHAR nfTmpStr[10];
CHAR tmpNumStr[24];
CHAR totFSStr[24];
CHAR msgStr[GLMAXPATH];
CHAR searchStr[GLMAXPATH];
CHAR tStr[GLMAXPATH];
CHAR hdrStr[GLMAXPATH+40];
div_t dvt;
CHAR ndTmpStr[40];
INT nd;
CHAR dTopFold[GLMAXPATH];
ULONG cfsize = sizeof(dTopFold);
HWND hwndF;
WPObject *sSelf;
ULONG drv;
CHAR totobjstr[24];
INT totobj;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


hwndF = (HWND)n;
sSelf = _wpclsQueryObjectFromFrame(_WPDesktop, hwndF);
if( !sSelf )
   return;
drv = _wpQueryLogicalDrive(sSelf);
strcpy(dTopFold, " :\\");
dTopFold[0] = (CHAR)(drv + '@'); 

STATSBUSY = 1;
if( hwndF != NULLHANDLE )
   {
   if( strlen(dTopFold) <= 3 )
      {
      if( strlen(dTopFold) < 2 )
         {
         STATSBUSY = 0;
         WinDestroyMsgQueue(hmqT);
         WinTerminate(habT);
         _endthread();
         }
      if( dTopFold[strlen(dTopFold)-1] != '\\' )
         {
         strcpy(tStr, dTopFold);
         strcat(tStr, "\\");
         }
      else
         strcpy(tStr, dTopFold);
      }
   else
      {
      for( ix=0;ix<strlen(dTopFold);ix++ )
         {
         if( dTopFold[ix] == '\\' )
            lastS = ix;
         }
      strncpy(tStr, dTopFold+(lastS+1), strlen(dTopFold)-(lastS));
      tStr[strlen(dTopFold)-(lastS)] = '\0';
      }

   strcpy(searchStr, dTopFold );
   totFS = 0;
   strcpy(tmpNumStr, "");
   strcpy(totFSStr, "");
   nf = searchP(searchStr);
   itoa(nf, nfTmpStr, 10);
   ltoa(totFS, tmpNumStr, 10);

   // GET NUMBER OF SUB DIRECTORIES
   nd = searchPDirs(searchStr);
   itoa(nd, ndTmpStr, 10);

   strcpy(nfstr, nfTmpStr);
   strcpy(totFSStr, tmpNumStr);
   addComa(nfstr);
   addComa(totFSStr);

   totobj = getObjCount(_wpQueryRootFolder(sSelf), tStr);
   if( totobj == -1 )
      return;
   itoa(totobj, totobjstr, 10);

   strcpy(msgStr, tStr);
   if( (pgmData[10] == 1 && pgmData[11] == 1 && nd == 0 && nf == 0) ||
       (pgmData[10] == 1 && pgmData[11] == 2 && nd == 0 && nf == 0 && totobj == 0) )
      {
      }
   else
      {   
      if( pgmData[4] == 1 )
         {
         // FILES
         strcat(msgStr, " - ");
         strcat(msgStr, "files: ");
         strcat(msgStr, nfstr);
         }
      if( pgmData[5] == 1 )
         {
         // BYTES
         strcat(msgStr, " - ");
         strcat(msgStr, "bytes: ");
         strcat(msgStr, totFSStr);
         }

      if( pgmData[6] == 1 )
         {
         // DIRECTORIES
         strcat(msgStr, " - ");
         strcat(msgStr, "dirs: ");
         strcat(msgStr, ndTmpStr);
         }
      
      if( pgmData[7] == 1 )
         {
         // OBJECTS
         strcat(msgStr, " - ");
         strcat(msgStr, "objs: ");
         strcat(msgStr, totobjstr);
         }
      }
         
   strcpy(hdrStr, "Folder stats : ");
   strcat(hdrStr, searchStr);


   if( hwndF )
      WinSetWindowText(WinWindowFromID(hwndF, FID_TITLEBAR), msgStr);
   }
   
STATSBUSY = 0;
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





INT searchPDirs(CHAR *schpath)
{
FILEFINDBUF3 findbuf;
HDIR hDir = HDIR_CREATE;
ULONG usSearchCount = 1;
INT nod;
CHAR schpathX[GLMAXPATH];
ULONG ALLFILES;
ULONG DIRFILES;

DIRFILES = FILE_DIRECTORY | FILE_HIDDEN;
ALLFILES = FILE_DIRECTORY | FILE_NORMAL | FILE_ARCHIVED | FILE_SYSTEM | FILE_READONLY | FILE_HIDDEN;
nod = 0;
memset(&findbuf,0,sizeof(FILEFINDBUF) );
if( schpath[strlen(schpath)-1] != '\\' )
   {
   strcpy(schpathX, schpath);
   strcat(schpathX, "\\*");
   }
else
   {
   strcpy(schpathX, schpath);
   strcat(schpathX, "*");
   }
if(DosFindFirst(schpathX, &hDir, ALLFILES, (PVOID)&findbuf, sizeof(findbuf), &usSearchCount, FIL_STANDARD))
   {
   DosFindClose(hDir);
   return(0);
   }
while (usSearchCount)
   {
   if ((findbuf.attrFile&FILE_DIRECTORY) && stricmp(findbuf.achName, ".") !=0 &&
                                                         stricmp(findbuf.achName, "..") !=0)
      {
      nod++;
      }
   if(DosFindNext(hDir, &findbuf, sizeof(findbuf), &usSearchCount))
      break;
   }
DosFindClose(hDir);
return(nod);
}





INT searchP(CHAR *schpath)
{
INT nof;
FILEFINDBUF3 findbuf;
HDIR hDir = HDIR_CREATE;
ULONG usSearchCount = 1;
ULONG ALLFILES;
CHAR sPath[GLMAXPATH];

nof = 0;
strcpy(sPath, schpath);
if( sPath[strlen(sPath)-1] != '\\' )
   strcat(sPath, "\\*");
else
   strcat(sPath, "*");
ALLFILES = FILE_NORMAL | FILE_ARCHIVED | FILE_SYSTEM | FILE_READONLY | FILE_HIDDEN;

if(DosFindFirst(sPath, &hDir, ALLFILES, (PVOID)&findbuf, sizeof(findbuf), &usSearchCount, FIL_STANDARD))
   {
   DosFindClose(hDir);
   return(0);
   }
else
   {
   nof++;
   totFS += findbuf.cbFile;
   }
while (usSearchCount)
   {
   if(DosFindNext(hDir, &findbuf, sizeof(findbuf), &usSearchCount))
      break;
   nof++;
   totFS += findbuf.cbFile;
   }
DosFindClose(hDir);
return(nof);
}





ULONG findDirList(CHAR *pcCurrentPath)
{
FILEFINDBUF3 findbuf;
HDIR hDir = HDIR_CREATE;
ULONG usSearchCount = 1;
CHAR schpath[_MAX_PATH] = "";
CHAR newline[] = "\n";
CHAR uscore[] = "_";
ULONG bwrote;
ULONG ppos;
ULONG bytesF;
ULONG ALLFILES;

ALLFILES = FILE_DIRECTORY | FILE_NORMAL | FILE_ARCHIVED | FILE_SYSTEM | FILE_READONLY | FILE_HIDDEN;
memset(&findbuf,0,sizeof(FILEFINDBUF) );
if( pcCurrentPath[strlen(pcCurrentPath)-1] != '\\' )
   {
   strcpy(schpath, pcCurrentPath);
   strcat(schpath, "\\*");
   }
else
   {
   strcpy(schpath, pcCurrentPath);
   strcat(schpath, "*");
   }
if(DosFindFirst(schpath, &hDir, ALLFILES, (PVOID)&findbuf, sizeof(findbuf), &usSearchCount, FIL_STANDARD))
   {
   DosFindClose(hDir);
   return(0);
   }
while (usSearchCount)
   {
   if ((findbuf.attrFile&FILE_DIRECTORY) && stricmp(findbuf.achName, ".") !=0 &&
                                                         stricmp(findbuf.achName, "..") !=0)
      {
      CHAR fqPath[_MAX_PATH] = "";

      TOTDIRS++;
      strcpy(fqPath, pcCurrentPath);
      if( fqPath[strlen(fqPath)-1] != '\\' )
         strcat(fqPath, "\\");
      strcat(fqPath, findbuf.achName);
      bytesF = findFiles(fqPath);
      bytesTotF = bytesTotF + bytesF;
      findDirList(fqPath);
      }
   if(DosFindNext(hDir, &findbuf, sizeof(findbuf), &usSearchCount))
      break;
   }
DosFindClose(hDir);
return(bytesTotF);
}





ULONG findFiles(CHAR *curPath)
{
FILEFINDBUF3 findbuf;
HDIR hDir = HDIR_CREATE;
ULONG usSearchCount = 1;
CHAR schpath[_MAX_PATH] = "";
ULONG bytes, bytesTot;
ULONG ALLFILES;
BOOL FFMASK, FILEMASK, ARC, HID, RDO, SYS;


ALLFILES = FILE_NORMAL | FILE_ARCHIVED | FILE_SYSTEM | FILE_READONLY | FILE_HIDDEN;
bytes = 0;
bytesTot = 0;
memset(&findbuf,0,sizeof(FILEFINDBUF3) );
if( curPath[strlen(curPath)-1] != '\\' )
   {
   strcpy(schpath, curPath);
   strcat(schpath, "\\*");
   }
else
   {
   strcpy(schpath, curPath);
   strcat(schpath, "*");
   }

if(DosFindFirst(schpath, &hDir, ALLFILES, (PVOID)&findbuf, sizeof(findbuf), &usSearchCount, FIL_STANDARD))
   {
   DosFindClose(hDir);
   return(0);
   }
while (usSearchCount)
   {
   bytesTot += findbuf.cbFile;
   totFiles++;
   if(DosFindNext(hDir, &findbuf, sizeof(findbuf), &usSearchCount))
      break;
   }
DosFindClose(hDir);
return(bytesTot);
}





char * strinsert(char *s, char insert)
{
char *sptr;

sptr = (char*)calloc(strlen(s)+1, sizeof(char));

if( sptr == NULL )
   return(NULL);

strcpy(sptr, s);
*s = insert;
strcpy(s+1, sptr);
free(sptr);
return(s);
}





VOID msgBox(HWND hwnd, CHAR *title, CHAR *message)
{
WinMessageBox(HWND_DESKTOP,
                     hwnd,
                     message,
                     title,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}




INT msgBoxOKCANCEL(HWND hwndDlg, CHAR *title, CHAR *msg)
{
if ( WinMessageBox(HWND_DESKTOP,
                          hwndDlg,
                          msg,
                          title,
                          0,
                          MB_ICONEXCLAMATION | MB_OKCANCEL) == MBID_CANCEL )
   {
   return(0);
   }
else
   return(1);
}






VOID saveSet(VOID)
{
HINI MYHINI;

if ( (MYHINI = PrfOpenProfile(0, STATSINI )) != NULLHANDLE )
   {
   PrfWriteProfileData(MYHINI,
                               "STATS",
                               "STATSSET",
                               &pgmData,
                               sizeof(pgmData));

   PrfWriteProfileString(MYHINI, "STATS",
                                 "SCODE", SCODE);
   }                   
}






VOID querySet(VOID)
{
HINI MYHINI;
ULONG rsizeX;


if ( (MYHINI = PrfOpenProfile(0, STATSINI )) != NULLHANDLE )
   {
   PrfQueryProfileSize(MYHINI,
                               "STATS",
                               "STATSSET", &rsizeX);
   if ( rsizeX == (sizeof(pgmData)) )
      {
      PrfQueryProfileData(MYHINI,
                                   "STATS",
                                   "STATSSET",
                                   &pgmData, &rsizeX);
      }
   else
      {
      pgmData[0] = 0;
      pgmData[1] = 0;
      pgmData[2] = 0;
      pgmData[3] = 0;
      pgmData[4] = 1;
      pgmData[5] = 1;
      pgmData[6] = 1;
      pgmData[7] = 1;
      pgmData[8] = 1;
      pgmData[9] = 0;
      pgmData[10] = 0;
      pgmData[11] = 1;
      pgmData[12] = 0;
      pgmData[13] = 0;
      pgmData[14] = 0;
      pgmData[15] = 0;
      pgmData[16] = 0;
      pgmData[17] = 0;
      pgmData[18] = 0;
      pgmData[19] = 0;
      pgmData[20] = 0;
      pgmData[21] = 0;
      pgmData[22] = 0;
      pgmData[23] = 0;
      pgmData[24] = 0;
      pgmData[25] = 0;
      pgmData[26] = 0;
      pgmData[27] = 0;
      pgmData[28] = 0;
      pgmData[29] = 0;
      pgmData[30] = 0;
      }
   PrfQueryProfileString(MYHINI, "STATS", "SCODE",
                                 "", SCODE, GLMAXPATH);
   }
else
   {
   pgmData[0] = 0;
   pgmData[1] = 0;
   pgmData[2] = 0;
   pgmData[3] = 0;
   pgmData[4] = 1;
   pgmData[5] = 1;
   pgmData[6] = 1;
   pgmData[7] = 1;
   pgmData[8] = 1;
   pgmData[9] = 0;
   pgmData[10] = 0;
   pgmData[11] = 1;
   pgmData[12] = 0;
   pgmData[13] = 0;
   pgmData[14] = 0;
   pgmData[15] = 0;
   pgmData[16] = 0;
   pgmData[17] = 0;
   pgmData[18] = 0;
   pgmData[19] = 0;
   pgmData[20] = 0;
   pgmData[21] = 0;
   pgmData[22] = 0;
   pgmData[23] = 0;
   pgmData[24] = 0;
   pgmData[25] = 0;
   pgmData[26] = 0;
   pgmData[27] = 0;
   pgmData[28] = 0;
   pgmData[29] = 0;
   pgmData[30] = 0;
   PrfQueryProfileString(MYHINI, "STATS", "SCODE",
                                 "", SCODE, GLMAXPATH);
   }                   
}







INT chkreg(VOID)
{
if(strlen(SCODE) == 13)
   {
   if( stricmp(SCODE, ",.,.,.,.,.,.,") == 0 || stricmp(SCODE, ".......==zz==") == 0 || stricmp(SCODE, "...=======...") == 0 )
      return(1);
   else
      return(0);   
   }
else
   return(0);   
}



VOID _Optlink payUp(PVOID n)
{
HAB habT;
HMQ hmqT;
HWND hwndDlg, hwndL;

habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


msgBox(HWND_DESKTOP, "Attention!", "The regestered version Stats doesn't do this.");


WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





VOID _Optlink getINIFQNAME(PVOID n)
{
APIRET rc;
CHAR fqprogPath[GLMAXPATH];
CHAR progPath[GLMAXPATH];
HAB habT;
HMQ hmqT;
HWND hwndDlg, hwndL;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

querySet();
PrfQueryProfileString(HINI_USERPROFILE, 
                               "StatsIsInstalled", 
                               "rc",
	        	       "", SCODE, 
		       GLMAXPATH);
saveSet();
rc = DosQueryModuleName(hResource,  sizeof(fqprogPath), fqprogPath);                     
if( rc == 0 )                     
   {
   INT num, mark;
 
   strcpy(progPath, fqprogPath);
   mark = -1;
   for( num=0;num<strlen(fqprogPath);num++ )
      {
      if( fqprogPath[num] == '\\' )
         mark = num;
      }
   if( mark )
      progPath[mark] = '\0';
   }
strcpy(fqprogPath, progPath);   
strcpy(STATSINI, progPath);
if( strlen(STATSINI) > 1 )
   {
   if( STATSINI[strlen(STATSINI) - 1] != '\\' )
      strcat(STATSINI, "\\");
   strcat(STATSINI, "STATS.INI");
   if( strlen(fqprogPath) > 4 && fqprogPath[strlen(fqprogPath)-1] == '\\' )
      fqprogPath[strlen(fqprogPath)-1] = '\0';   
   PrfWriteProfileString(HINI_USERPROFILE, 
                              "StatsIsInstalled",
                              "InstallationPath", 
                              fqprogPath);
   }
         
WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





VOID debugMsgStr(CHAR *str, CHAR *varName)
{
CHAR dMsg[255] = "Debug Message string ... ";

strcat(dMsg, varName),
WinMessageBox(HWND_DESKTOP,
              HWND_DESKTOP,
              str,
              dMsg,
              0,
              MB_OK | MB_ICONEXCLAMATION );
}




VOID debugMsgInt(INT num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message Int ... ";

strcat(dMsg, varName),
itoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
              HWND_DESKTOP,
              str,
              dMsg,
              0,
              MB_OK | MB_ICONEXCLAMATION );
}




VOID debugMsgULong(ULONG num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message ULong ... ";

strcat(dMsg, varName),
ultoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
              HWND_DESKTOP,
              str,
              dMsg,
              0,
              MB_OK | MB_ICONEXCLAMATION );
}





VOID debugMsgLong(LONG num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message Long ... ";

strcat(dMsg, varName),
ltoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
              HWND_DESKTOP,
              str,
              dMsg,
              0,
              MB_OK | MB_ICONEXCLAMATION );
}




VOID debugMsgCH(CHAR ch, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message char ... ";

strcat(dMsg, varName),
str[0] = ch;
str[1] = '\0';
WinMessageBox(HWND_DESKTOP,
              HWND_DESKTOP,
              str,
              dMsg,
              0,
              MB_OK | MB_ICONEXCLAMATION );
}











