
/*
 * This file was generated by the SOM Compiler.
 * FileName: H:\stats\WPSDLL\stats.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 *    STATS.IDL - A WorkFrame/2* Quickstart WPS/SOM application
 * 
 */


#ifndef SOM_stats_h
#define SOM_stats_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef stats
#define stats SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef WPRootFolder
    #define WPRootFolder SOMObject
#endif /* WPRootFolder */
#ifndef M_WPDisk
    #define M_WPDisk SOMObject
#endif /* M_WPDisk */
#ifndef M_WPRootFolder
    #define M_WPRootFolder SOMObject
#endif /* M_WPRootFolder */
#ifndef M_stats
    #define M_stats SOMObject
#endif /* M_stats */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_statsfile
    #define M_statsfile SOMObject
#endif /* M_statsfile */
#ifndef M_statsdisk
    #define M_statsdisk SOMObject
#endif /* M_statsdisk */

/*
 * End of user-defined types.
 */

#define stats_MajorVersion 1
#define stats_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define statsNewClass statsc
#pragma linkage(statsc, system)
#define statsClassData statsd
#define statsCClassData statsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <stats.h>
/*--------------Migration------------*/
#define stats_classObj statsClassData.classObject
#define _stats stats_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK statsNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(statsNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct statsClassDataStructure {
	SOMClass *classObject;
} SOMDLINK statsClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct statsCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK statsCClassData;

/*
 * New and Renew macros for stats
 */
#define statsNew() \
   (_somNew(_stats ? _stats : statsNewClass(stats_MajorVersion, stats_MinorVersion)))
#define statsRenew(buf) \
   (_somRenew(_stats ? _stats : statsNewClass(stats_MajorVersion, stats_MinorVersion), buf))

/*
 * Override method: wpModifyPopupMenu
 */
#define stats_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define stats_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpViewObject
 */
#define stats_wpViewObject(somSelf,hwndCnr,ulView,param) \
	WPObject_wpViewObject(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpOpen
 */
#define stats_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpAddToContent
 */
#define stats_wpAddToContent(somSelf,Object) \
	WPFolder_wpAddToContent(somSelf,Object)

/*
 * Override method: wpDeleteFromContent
 */
#define stats_wpDeleteFromContent(somSelf,Object) \
	WPFolder_wpDeleteFromContent(somSelf,Object)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define stats_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define stats_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define stats_wpSetFldrFont WPFolder_wpSetFldrFont
#define stats_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define stats_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define stats_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define stats_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define stats_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define stats_wpPopulate WPFolder_wpPopulate
#define stats_wpQueryContent WPFolder_wpQueryContent
#define stats_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define stats_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define stats_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define stats_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define stats_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define stats_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define stats_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define stats_wpInitIconPosData WPFolder_wpInitIconPosData
#define stats_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define stats_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define stats_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define stats_wpSetFldrSort WPFolder_wpSetFldrSort
#define stats_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define stats_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define stats_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define stats_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define stats_wpDeleteContents WPFolder_wpDeleteContents
#define stats_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define stats_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define stats_wpSearchFolder WPFolder_wpSearchFolder
#define stats_wpContainsFolders WPFolder_wpContainsFolders
#define stats_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define stats_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define stats_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define stats_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define stats_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define stats_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define stats_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define stats_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define stats_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define stats_wpAddFirstChild WPFolder_wpAddFirstChild
#define stats_wpSetRealName WPFileSystem_wpSetRealName
#define stats_wpSetType WPFileSystem_wpSetType
#define stats_wpQueryType WPFileSystem_wpQueryType
#define stats_wpSetAttr WPFileSystem_wpSetAttr
#define stats_wpQueryAttr WPFileSystem_wpQueryAttr
#define stats_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define stats_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define stats_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define stats_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define stats_wpQueryCreation WPFileSystem_wpQueryCreation
#define stats_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define stats_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define stats_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define stats_wpQueryEASize WPFileSystem_wpQueryEASize
#define stats_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define stats_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define stats_wpRefresh WPFileSystem_wpRefresh
#define stats_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define stats_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define stats_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define stats_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define stats_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define stats_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define stats_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define stats_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define stats_wpQueryRealName WPFileSystem_wpQueryRealName
#define stats_wpQueryFilename WPFileSystem_wpQueryFilename
#define stats_wpQueryDisk WPFileSystem_wpQueryDisk
#define stats_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define stats_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define stats_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define stats_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define stats_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define stats_wpAddSettingsPages WPObject_wpAddSettingsPages
#define stats_wpAddToObjUseList WPObject_wpAddToObjUseList
#define stats_wpAllocMem WPObject_wpAllocMem
#define stats_wpAppendObject WPObject_wpAppendObject
#define stats_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define stats_wpClose WPObject_wpClose
#define stats_wpCnrInsertObject WPObject_wpCnrInsertObject
#define stats_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define stats_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define stats_wpConfirmDelete WPObject_wpConfirmDelete
#define stats_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define stats_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define stats_wpCopyObject WPObject_wpCopyObject
#define stats_wpCreateAnother WPObject_wpCreateAnother
#define stats_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define stats_wpCreateShadowObject WPObject_wpCreateShadowObject
#define stats_wpDelete WPObject_wpDelete
#define stats_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define stats_wpDisplayHelp WPObject_wpDisplayHelp
#define stats_wpDisplayMenu WPObject_wpDisplayMenu
#define stats_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define stats_wpDraggedOverObject WPObject_wpDraggedOverObject
#define stats_wpDragOver WPObject_wpDragOver
#define stats_wpDrop WPObject_wpDrop
#define stats_wpDroppedOnObject WPObject_wpDroppedOnObject
#define stats_wpEndConversation WPObject_wpEndConversation
#define stats_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define stats_wpFindUseItem WPObject_wpFindUseItem
#define stats_wpFormatDragItem WPObject_wpFormatDragItem
#define stats_wpFree WPObject_wpFree
#define stats_wpFreeMem WPObject_wpFreeMem
#define stats_wpHide WPObject_wpHide
#define stats_wpInitData WPObject_wpInitData
#define stats_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define stats_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define stats_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define stats_wpMoveObject WPObject_wpMoveObject
#define stats_wpPrintObject WPObject_wpPrintObject
#define stats_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define stats_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define stats_wpQueryConfirmations WPObject_wpQueryConfirmations
#define stats_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define stats_wpQueryDefaultView WPObject_wpQueryDefaultView
#define stats_wpQueryDetailsData WPObject_wpQueryDetailsData
#define stats_wpQueryError WPObject_wpQueryError
#define stats_wpSetFolder WPObject_wpSetFolder
#define stats_wpQueryFolder WPObject_wpQueryFolder
#define stats_wpQueryIcon WPObject_wpQueryIcon
#define stats_wpQueryIconData WPObject_wpQueryIconData
#define stats_wpQueryMinWindow WPObject_wpQueryMinWindow
#define stats_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define stats_wpQueryStyle WPObject_wpQueryStyle
#define stats_wpSetTaskRec WPObject_wpSetTaskRec
#define stats_wpFindTaskRec WPObject_wpFindTaskRec
#define stats_wpQueryTitle WPObject_wpQueryTitle
#define stats_wpRegisterView WPObject_wpRegisterView
#define stats_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define stats_wpRender WPObject_wpRender
#define stats_wpRenderComplete WPObject_wpRenderComplete
#define stats_wpReplaceObject WPObject_wpReplaceObject
#define stats_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define stats_wpRestore WPObject_wpRestore
#define stats_wpRestoreData WPObject_wpRestoreData
#define stats_wpRestoreLong WPObject_wpRestoreLong
#define stats_wpRestoreState WPObject_wpRestoreState
#define stats_wpRestoreString WPObject_wpRestoreString
#define stats_wpSaveData WPObject_wpSaveData
#define stats_wpSaveImmediate WPObject_wpSaveImmediate
#define stats_wpSaveDeferred WPObject_wpSaveDeferred
#define stats_wpSaveLong WPObject_wpSaveLong
#define stats_wpSaveState WPObject_wpSaveState
#define stats_wpSaveString WPObject_wpSaveString
#define stats_wpScanSetupString WPObject_wpScanSetupString
#define stats_wpSetConcurrentView WPObject_wpSetConcurrentView
#define stats_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define stats_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define stats_wpSetDefaultView WPObject_wpSetDefaultView
#define stats_wpSetError WPObject_wpSetError
#define stats_wpSetIconHandle WPObject_wpSetIconHandle
#define stats_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define stats_wpSetupOnce WPObject_wpSetupOnce
#define stats_wpSetIcon WPObject_wpSetIcon
#define stats_wpSetIconData WPObject_wpSetIconData
#define stats_wpSetMinWindow WPObject_wpSetMinWindow
#define stats_wpSetStyle WPObject_wpSetStyle
#define stats_wpModifyStyle WPObject_wpModifyStyle
#define stats_wpSetTitle WPObject_wpSetTitle
#define stats_wpSetup WPObject_wpSetup
#define stats_wpSwitchTo WPObject_wpSwitchTo
#define stats_wpUnInitData WPObject_wpUnInitData
#define stats_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define stats_wpQueryHandle WPObject_wpQueryHandle
#define stats_wpUnlockObject WPObject_wpUnlockObject
#define stats_wpObjectReady WPObject_wpObjectReady
#define stats_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define stats_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define stats_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define stats_wpIsDeleteable WPObject_wpIsDeleteable
#define stats_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define stats_wpSetObjectID WPObject_wpSetObjectID
#define stats_wpQueryObjectID WPObject_wpQueryObjectID
#define stats_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define stats_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define stats_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define stats_wpFindViewItem WPObject_wpFindViewItem
#define stats_wpLockObject WPObject_wpLockObject
#define stats_wpIsLocked WPObject_wpIsLocked
#define stats_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define stats_wpWaitForClose WPObject_wpWaitForClose
#define stats_somDefaultInit SOMObject_somDefaultInit
#define stats_somDestruct SOMObject_somDestruct
#define stats_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define stats_somDefaultAssign SOMObject_somDefaultAssign
#define stats_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define stats_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define stats_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define stats_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define stats_somDefaultVAssign SOMObject_somDefaultVAssign
#define stats_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define stats_somInit SOMObject_somInit
#define stats_somFree SOMObject_somFree
#define stats_somUninit SOMObject_somUninit
#define stats_somGetClass SOMObject_somGetClass
#define stats_somGetClassName SOMObject_somGetClassName
#define stats_somGetSize SOMObject_somGetSize
#define stats_somIsA SOMObject_somIsA
#define stats_somIsInstanceOf SOMObject_somIsInstanceOf
#define stats_somRespondsTo SOMObject_somRespondsTo
#define stats_somDispatch SOMObject_somDispatch
#define stats_somClassDispatch SOMObject_somClassDispatch
#define stats_somCastObj SOMObject_somCastObj
#define stats_somResetObj SOMObject_somResetObj
#define stats_somDispatchV SOMObject_somDispatchV
#define stats_somDispatchL SOMObject_somDispatchL
#define stats_somDispatchA SOMObject_somDispatchA
#define stats_somDispatchD SOMObject_somDispatchD
#define stats_somPrintSelf SOMObject_somPrintSelf
#define stats_somDumpSelf SOMObject_somDumpSelf
#define stats_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_stats_h */

#ifndef SOM_M_stats_h
#define SOM_M_stats_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_stats
#define M_stats SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_stats_HMODULE;
typedef
unsigned long  M_stats_HPOINTER;
typedef
string  M_stats_PSZ;

/*
 *  New class methods
 *  HMODULE clsGetResourceModule();
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_stats_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_stats_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_stats_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_stats_MajorVersion 1
#define M_stats_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_statsNewClass statsc
#pragma linkage(statsc, system)
#define M_statsClassData statsd
#define M_statsCClassData statsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_stats_classObj M_statsClassData.classObject
#define _M_stats M_stats_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_statsNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_statsNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_statsClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
} SOMDLINK M_statsClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_statsCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_statsCClassData;

/*
 * New and Renew macros for M_stats
 */
#define M_statsNew() \
   (_somNew(_M_stats ? _M_stats : M_statsNewClass(M_stats_MajorVersion, M_stats_MinorVersion)))
#define M_statsRenew(buf) \
   (_somRenew(_M_stats ? _M_stats : M_statsNewClass(M_stats_MajorVersion, M_stats_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_stats_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_stats_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_stats_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_stats_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_stats_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_stats_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_stats_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_stats_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_stats_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_stats_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_stats_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_stats_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_stats_wpclsNew M_WPObject_wpclsNew
#define M_stats_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_stats_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_stats_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_stats_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_stats_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_stats_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_stats_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_stats_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_stats_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_stats_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_stats_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_stats_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_stats_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_stats_wpclsSetError M_WPObject_wpclsSetError
#define M_stats_wpclsQueryError M_WPObject_wpclsQueryError
#define M_stats_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_stats_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_stats_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_stats_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_stats_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_stats_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_stats_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_stats_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_stats_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_stats_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_stats_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_stats_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_stats_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_stats__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_stats__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_stats__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_stats__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_stats_somNew SOMClass_somNew
#define M_stats_somNewNoInit SOMClass_somNewNoInit
#define M_stats_somRenew SOMClass_somRenew
#define M_stats_somRenewNoInit SOMClass_somRenewNoInit
#define M_stats_somRenewNoZero SOMClass_somRenewNoZero
#define M_stats_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_stats_somAllocate SOMClass_somAllocate
#define M_stats_somDeallocate SOMClass_somDeallocate
#define M_stats__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_stats__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_stats_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_stats_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_stats_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_stats_somInitClass SOMClass_somInitClass
#define M_stats_somInitMIClass SOMClass_somInitMIClass
#define M_stats_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_stats_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_stats_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_stats_somClassReady SOMClass_somClassReady
#define M_stats_somGetApplyStub SOMClass_somGetApplyStub
#define M_stats_somGetClassData SOMClass_somGetClassData
#define M_stats_somSetClassData SOMClass_somSetClassData
#define M_stats_somGetClassMtab SOMClass_somGetClassMtab
#define M_stats_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_stats_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_stats_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_stats_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_stats_somGetMemberToken SOMClass_somGetMemberToken
#define M_stats_somGetMethodData SOMClass_somGetMethodData
#define M_stats_somGetRdStub SOMClass_somGetRdStub
#define M_stats_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_stats_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_stats_somGetMethodToken SOMClass_somGetMethodToken
#define M_stats_somGetName SOMClass_somGetName
#define M_stats_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_stats_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_stats_somGetNumMethods SOMClass_somGetNumMethods
#define M_stats_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_stats_somGetParent SOMClass_somGetParent
#define M_stats_somGetParents SOMClass_somGetParents
#define M_stats_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_stats_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_stats_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_stats_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_stats_somFindMethod SOMClass_somFindMethod
#define M_stats_somFindMethodOk SOMClass_somFindMethodOk
#define M_stats_somFindSMethod SOMClass_somFindSMethod
#define M_stats_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_stats_somLookupMethod SOMClass_somLookupMethod
#define M_stats_somCheckVersion SOMClass_somCheckVersion
#define M_stats_somDescendedFrom SOMClass_somDescendedFrom
#define M_stats_somSupportsMethod SOMClass_somSupportsMethod
#define M_stats_somDefinedMethod SOMClass_somDefinedMethod
#define M_stats_somOverrideMtab SOMClass_somOverrideMtab
#define M_stats_somDefaultInit SOMObject_somDefaultInit
#define M_stats_somDestruct SOMObject_somDestruct
#define M_stats_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_stats_somDefaultAssign SOMObject_somDefaultAssign
#define M_stats_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_stats_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_stats_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_stats_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_stats_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_stats_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_stats_somInit SOMObject_somInit
#define M_stats_somFree SOMObject_somFree
#define M_stats_somUninit SOMObject_somUninit
#define M_stats_somGetClass SOMObject_somGetClass
#define M_stats_somGetClassName SOMObject_somGetClassName
#define M_stats_somGetSize SOMObject_somGetSize
#define M_stats_somIsA SOMObject_somIsA
#define M_stats_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_stats_somRespondsTo SOMObject_somRespondsTo
#define M_stats_somDispatch SOMObject_somDispatch
#define M_stats_somClassDispatch SOMObject_somClassDispatch
#define M_stats_somCastObj SOMObject_somCastObj
#define M_stats_somResetObj SOMObject_somResetObj
#define M_stats_somDispatchV SOMObject_somDispatchV
#define M_stats_somDispatchL SOMObject_somDispatchL
#define M_stats_somDispatchA SOMObject_somDispatchA
#define M_stats_somDispatchD SOMObject_somDispatchD
#define M_stats_somPrintSelf SOMObject_somPrintSelf
#define M_stats_somDumpSelf SOMObject_somDumpSelf
#define M_stats_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_stats_h */

#ifndef SOM_statsfile_h
#define SOM_statsfile_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef statsfile
#define statsfile SOMObject
#endif
#include <wpdataf.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define statsfile_MajorVersion 1
#define statsfile_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define statsfileNewClass statsfilec
#pragma linkage(statsfilec, system)
#define statsfileClassData statsfiled
#define statsfileCClassData statsfilex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <stats.h>
/*--------------Migration------------*/
#define statsfile_classObj statsfileClassData.classObject
#define _statsfile statsfile_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK statsfileNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(statsfileNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct statsfileClassDataStructure {
	SOMClass *classObject;
} SOMDLINK statsfileClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct statsfileCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK statsfileCClassData;

/*
 * New and Renew macros for statsfile
 */
#define statsfileNew() \
   (_somNew(_statsfile ? _statsfile : statsfileNewClass(statsfile_MajorVersion, statsfile_MinorVersion)))
#define statsfileRenew(buf) \
   (_somRenew(_statsfile ? _statsfile : statsfileNewClass(statsfile_MajorVersion, statsfile_MinorVersion), buf))

/*
 * Override method: wpInitData
 */
#define statsfile_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define statsfile_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpModifyPopupMenu
 */
#define statsfile_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define statsfile_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define statsfile_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define statsfile_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define statsfile_wpPrintPifFile WPDataFile_wpPrintPifFile
#define statsfile_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define statsfile_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define statsfile_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define statsfile_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define statsfile_wpQueryAssociatedFileIcon WPDataFile_wpQueryAssociatedFileIcon
#define statsfile_wpSetRealName WPFileSystem_wpSetRealName
#define statsfile_wpSetType WPFileSystem_wpSetType
#define statsfile_wpQueryType WPFileSystem_wpQueryType
#define statsfile_wpSetAttr WPFileSystem_wpSetAttr
#define statsfile_wpQueryAttr WPFileSystem_wpQueryAttr
#define statsfile_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define statsfile_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define statsfile_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define statsfile_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define statsfile_wpQueryCreation WPFileSystem_wpQueryCreation
#define statsfile_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define statsfile_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define statsfile_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define statsfile_wpQueryEASize WPFileSystem_wpQueryEASize
#define statsfile_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define statsfile_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define statsfile_wpRefresh WPFileSystem_wpRefresh
#define statsfile_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define statsfile_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define statsfile_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define statsfile_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define statsfile_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define statsfile_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define statsfile_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define statsfile_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define statsfile_wpQueryRealName WPFileSystem_wpQueryRealName
#define statsfile_wpQueryFilename WPFileSystem_wpQueryFilename
#define statsfile_wpQueryDisk WPFileSystem_wpQueryDisk
#define statsfile_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define statsfile_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define statsfile_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define statsfile_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define statsfile_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define statsfile_wpAddSettingsPages WPObject_wpAddSettingsPages
#define statsfile_wpAddToObjUseList WPObject_wpAddToObjUseList
#define statsfile_wpAllocMem WPObject_wpAllocMem
#define statsfile_wpAppendObject WPObject_wpAppendObject
#define statsfile_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define statsfile_wpClose WPObject_wpClose
#define statsfile_wpCnrInsertObject WPObject_wpCnrInsertObject
#define statsfile_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define statsfile_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define statsfile_wpConfirmDelete WPObject_wpConfirmDelete
#define statsfile_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define statsfile_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define statsfile_wpCopyObject WPObject_wpCopyObject
#define statsfile_wpCreateAnother WPObject_wpCreateAnother
#define statsfile_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define statsfile_wpCreateShadowObject WPObject_wpCreateShadowObject
#define statsfile_wpDelete WPObject_wpDelete
#define statsfile_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define statsfile_wpDisplayHelp WPObject_wpDisplayHelp
#define statsfile_wpDisplayMenu WPObject_wpDisplayMenu
#define statsfile_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define statsfile_wpDraggedOverObject WPObject_wpDraggedOverObject
#define statsfile_wpDragOver WPObject_wpDragOver
#define statsfile_wpDrop WPObject_wpDrop
#define statsfile_wpDroppedOnObject WPObject_wpDroppedOnObject
#define statsfile_wpEndConversation WPObject_wpEndConversation
#define statsfile_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define statsfile_wpFindUseItem WPObject_wpFindUseItem
#define statsfile_wpFormatDragItem WPObject_wpFormatDragItem
#define statsfile_wpFree WPObject_wpFree
#define statsfile_wpFreeMem WPObject_wpFreeMem
#define statsfile_wpHide WPObject_wpHide
#define statsfile_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define statsfile_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define statsfile_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define statsfile_wpMoveObject WPObject_wpMoveObject
#define statsfile_wpOpen WPObject_wpOpen
#define statsfile_wpPrintObject WPObject_wpPrintObject
#define statsfile_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define statsfile_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define statsfile_wpQueryConfirmations WPObject_wpQueryConfirmations
#define statsfile_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define statsfile_wpQueryDefaultView WPObject_wpQueryDefaultView
#define statsfile_wpQueryDetailsData WPObject_wpQueryDetailsData
#define statsfile_wpQueryError WPObject_wpQueryError
#define statsfile_wpSetFolder WPObject_wpSetFolder
#define statsfile_wpQueryFolder WPObject_wpQueryFolder
#define statsfile_wpQueryIcon WPObject_wpQueryIcon
#define statsfile_wpQueryIconData WPObject_wpQueryIconData
#define statsfile_wpQueryMinWindow WPObject_wpQueryMinWindow
#define statsfile_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define statsfile_wpQueryStyle WPObject_wpQueryStyle
#define statsfile_wpSetTaskRec WPObject_wpSetTaskRec
#define statsfile_wpFindTaskRec WPObject_wpFindTaskRec
#define statsfile_wpQueryTitle WPObject_wpQueryTitle
#define statsfile_wpRegisterView WPObject_wpRegisterView
#define statsfile_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define statsfile_wpRender WPObject_wpRender
#define statsfile_wpRenderComplete WPObject_wpRenderComplete
#define statsfile_wpReplaceObject WPObject_wpReplaceObject
#define statsfile_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define statsfile_wpRestore WPObject_wpRestore
#define statsfile_wpRestoreData WPObject_wpRestoreData
#define statsfile_wpRestoreLong WPObject_wpRestoreLong
#define statsfile_wpRestoreState WPObject_wpRestoreState
#define statsfile_wpRestoreString WPObject_wpRestoreString
#define statsfile_wpSaveData WPObject_wpSaveData
#define statsfile_wpSaveImmediate WPObject_wpSaveImmediate
#define statsfile_wpSaveDeferred WPObject_wpSaveDeferred
#define statsfile_wpSaveLong WPObject_wpSaveLong
#define statsfile_wpSaveState WPObject_wpSaveState
#define statsfile_wpSaveString WPObject_wpSaveString
#define statsfile_wpScanSetupString WPObject_wpScanSetupString
#define statsfile_wpSetConcurrentView WPObject_wpSetConcurrentView
#define statsfile_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define statsfile_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define statsfile_wpSetDefaultView WPObject_wpSetDefaultView
#define statsfile_wpSetError WPObject_wpSetError
#define statsfile_wpSetIconHandle WPObject_wpSetIconHandle
#define statsfile_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define statsfile_wpSetupOnce WPObject_wpSetupOnce
#define statsfile_wpSetIcon WPObject_wpSetIcon
#define statsfile_wpSetIconData WPObject_wpSetIconData
#define statsfile_wpSetMinWindow WPObject_wpSetMinWindow
#define statsfile_wpSetStyle WPObject_wpSetStyle
#define statsfile_wpModifyStyle WPObject_wpModifyStyle
#define statsfile_wpSetTitle WPObject_wpSetTitle
#define statsfile_wpSetup WPObject_wpSetup
#define statsfile_wpSwitchTo WPObject_wpSwitchTo
#define statsfile_wpViewObject WPObject_wpViewObject
#define statsfile_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define statsfile_wpQueryHandle WPObject_wpQueryHandle
#define statsfile_wpUnlockObject WPObject_wpUnlockObject
#define statsfile_wpObjectReady WPObject_wpObjectReady
#define statsfile_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define statsfile_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define statsfile_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define statsfile_wpIsDeleteable WPObject_wpIsDeleteable
#define statsfile_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define statsfile_wpSetObjectID WPObject_wpSetObjectID
#define statsfile_wpQueryObjectID WPObject_wpQueryObjectID
#define statsfile_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define statsfile_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define statsfile_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define statsfile_wpFindViewItem WPObject_wpFindViewItem
#define statsfile_wpLockObject WPObject_wpLockObject
#define statsfile_wpIsLocked WPObject_wpIsLocked
#define statsfile_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define statsfile_wpWaitForClose WPObject_wpWaitForClose
#define statsfile_somDefaultInit SOMObject_somDefaultInit
#define statsfile_somDestruct SOMObject_somDestruct
#define statsfile_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define statsfile_somDefaultAssign SOMObject_somDefaultAssign
#define statsfile_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define statsfile_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define statsfile_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define statsfile_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define statsfile_somDefaultVAssign SOMObject_somDefaultVAssign
#define statsfile_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define statsfile_somInit SOMObject_somInit
#define statsfile_somFree SOMObject_somFree
#define statsfile_somUninit SOMObject_somUninit
#define statsfile_somGetClass SOMObject_somGetClass
#define statsfile_somGetClassName SOMObject_somGetClassName
#define statsfile_somGetSize SOMObject_somGetSize
#define statsfile_somIsA SOMObject_somIsA
#define statsfile_somIsInstanceOf SOMObject_somIsInstanceOf
#define statsfile_somRespondsTo SOMObject_somRespondsTo
#define statsfile_somDispatch SOMObject_somDispatch
#define statsfile_somClassDispatch SOMObject_somClassDispatch
#define statsfile_somCastObj SOMObject_somCastObj
#define statsfile_somResetObj SOMObject_somResetObj
#define statsfile_somDispatchV SOMObject_somDispatchV
#define statsfile_somDispatchL SOMObject_somDispatchL
#define statsfile_somDispatchA SOMObject_somDispatchA
#define statsfile_somDispatchD SOMObject_somDispatchD
#define statsfile_somPrintSelf SOMObject_somPrintSelf
#define statsfile_somDumpSelf SOMObject_somDumpSelf
#define statsfile_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_statsfile_h */

#ifndef SOM_M_statsfile_h
#define SOM_M_statsfile_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_statsfile
#define M_statsfile SOMObject
#endif
#include <wpdataf.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_statsfile_HMODULE;
typedef
unsigned long  M_statsfile_HPOINTER;
typedef
string  M_statsfile_PSZ;

/*
 *  New class methods
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_statsfile_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_statsfile_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_statsfile_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_statsfile_MajorVersion 1
#define M_statsfile_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_statsfileNewClass statsfilec
#pragma linkage(statsfilec, system)
#define M_statsfileClassData statsfiled
#define M_statsfileCClassData statsfilex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_statsfile_classObj M_statsfileClassData.classObject
#define _M_statsfile M_statsfile_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_statsfileNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_statsfileNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_statsfileClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
} SOMDLINK M_statsfileClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_statsfileCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_statsfileCClassData;

/*
 * New and Renew macros for M_statsfile
 */
#define M_statsfileNew() \
   (_somNew(_M_statsfile ? _M_statsfile : M_statsfileNewClass(M_statsfile_MajorVersion, M_statsfile_MinorVersion)))
#define M_statsfileRenew(buf) \
   (_somRenew(_M_statsfile ? _M_statsfile : M_statsfileNewClass(M_statsfile_MajorVersion, M_statsfile_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_statsfile_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_statsfile_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_statsfile_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_statsfile_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_statsfile_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_statsfile_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_statsfile_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_statsfile_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_statsfile_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_statsfile_wpclsNew M_WPObject_wpclsNew
#define M_statsfile_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_statsfile_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_statsfile_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_statsfile_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_statsfile_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_statsfile_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_statsfile_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_statsfile_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_statsfile_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_statsfile_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_statsfile_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_statsfile_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_statsfile_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_statsfile_wpclsSetError M_WPObject_wpclsSetError
#define M_statsfile_wpclsQueryError M_WPObject_wpclsQueryError
#define M_statsfile_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_statsfile_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_statsfile_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_statsfile_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_statsfile_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_statsfile_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_statsfile_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_statsfile_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_statsfile_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_statsfile_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_statsfile_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_statsfile_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_statsfile_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_statsfile__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_statsfile__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_statsfile__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_statsfile__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_statsfile_somNew SOMClass_somNew
#define M_statsfile_somNewNoInit SOMClass_somNewNoInit
#define M_statsfile_somRenew SOMClass_somRenew
#define M_statsfile_somRenewNoInit SOMClass_somRenewNoInit
#define M_statsfile_somRenewNoZero SOMClass_somRenewNoZero
#define M_statsfile_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_statsfile_somAllocate SOMClass_somAllocate
#define M_statsfile_somDeallocate SOMClass_somDeallocate
#define M_statsfile__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_statsfile__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_statsfile_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_statsfile_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_statsfile_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_statsfile_somInitClass SOMClass_somInitClass
#define M_statsfile_somInitMIClass SOMClass_somInitMIClass
#define M_statsfile_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_statsfile_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_statsfile_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_statsfile_somClassReady SOMClass_somClassReady
#define M_statsfile_somGetApplyStub SOMClass_somGetApplyStub
#define M_statsfile_somGetClassData SOMClass_somGetClassData
#define M_statsfile_somSetClassData SOMClass_somSetClassData
#define M_statsfile_somGetClassMtab SOMClass_somGetClassMtab
#define M_statsfile_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_statsfile_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_statsfile_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_statsfile_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_statsfile_somGetMemberToken SOMClass_somGetMemberToken
#define M_statsfile_somGetMethodData SOMClass_somGetMethodData
#define M_statsfile_somGetRdStub SOMClass_somGetRdStub
#define M_statsfile_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_statsfile_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_statsfile_somGetMethodToken SOMClass_somGetMethodToken
#define M_statsfile_somGetName SOMClass_somGetName
#define M_statsfile_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_statsfile_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_statsfile_somGetNumMethods SOMClass_somGetNumMethods
#define M_statsfile_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_statsfile_somGetParent SOMClass_somGetParent
#define M_statsfile_somGetParents SOMClass_somGetParents
#define M_statsfile_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_statsfile_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_statsfile_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_statsfile_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_statsfile_somFindMethod SOMClass_somFindMethod
#define M_statsfile_somFindMethodOk SOMClass_somFindMethodOk
#define M_statsfile_somFindSMethod SOMClass_somFindSMethod
#define M_statsfile_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_statsfile_somLookupMethod SOMClass_somLookupMethod
#define M_statsfile_somCheckVersion SOMClass_somCheckVersion
#define M_statsfile_somDescendedFrom SOMClass_somDescendedFrom
#define M_statsfile_somSupportsMethod SOMClass_somSupportsMethod
#define M_statsfile_somDefinedMethod SOMClass_somDefinedMethod
#define M_statsfile_somOverrideMtab SOMClass_somOverrideMtab
#define M_statsfile_somDefaultInit SOMObject_somDefaultInit
#define M_statsfile_somDestruct SOMObject_somDestruct
#define M_statsfile_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_statsfile_somDefaultAssign SOMObject_somDefaultAssign
#define M_statsfile_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_statsfile_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_statsfile_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_statsfile_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_statsfile_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_statsfile_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_statsfile_somInit SOMObject_somInit
#define M_statsfile_somFree SOMObject_somFree
#define M_statsfile_somUninit SOMObject_somUninit
#define M_statsfile_somGetClass SOMObject_somGetClass
#define M_statsfile_somGetClassName SOMObject_somGetClassName
#define M_statsfile_somGetSize SOMObject_somGetSize
#define M_statsfile_somIsA SOMObject_somIsA
#define M_statsfile_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_statsfile_somRespondsTo SOMObject_somRespondsTo
#define M_statsfile_somDispatch SOMObject_somDispatch
#define M_statsfile_somClassDispatch SOMObject_somClassDispatch
#define M_statsfile_somCastObj SOMObject_somCastObj
#define M_statsfile_somResetObj SOMObject_somResetObj
#define M_statsfile_somDispatchV SOMObject_somDispatchV
#define M_statsfile_somDispatchL SOMObject_somDispatchL
#define M_statsfile_somDispatchA SOMObject_somDispatchA
#define M_statsfile_somDispatchD SOMObject_somDispatchD
#define M_statsfile_somPrintSelf SOMObject_somPrintSelf
#define M_statsfile_somDumpSelf SOMObject_somDumpSelf
#define M_statsfile_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_statsfile_h */

#ifndef SOM_statsdisk_h
#define SOM_statsdisk_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef statsdisk
#define statsdisk SOMObject
#endif
#include <wpdisk.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define statsdisk_MajorVersion 1
#define statsdisk_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define statsdiskNewClass statsdiskc
#pragma linkage(statsdiskc, system)
#define statsdiskClassData statsdiskd
#define statsdiskCClassData statsdiskx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <stats.h>
/*--------------Migration------------*/
#define statsdisk_classObj statsdiskClassData.classObject
#define _statsdisk statsdisk_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK statsdiskNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(statsdiskNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct statsdiskClassDataStructure {
	SOMClass *classObject;
} SOMDLINK statsdiskClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct statsdiskCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK statsdiskCClassData;

/*
 * New and Renew macros for statsdisk
 */
#define statsdiskNew() \
   (_somNew(_statsdisk ? _statsdisk : statsdiskNewClass(statsdisk_MajorVersion, statsdisk_MinorVersion)))
#define statsdiskRenew(buf) \
   (_somRenew(_statsdisk ? _statsdisk : statsdiskNewClass(statsdisk_MajorVersion, statsdisk_MinorVersion), buf))

/*
 * Override method: wpModifyPopupMenu
 */
#define statsdisk_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define statsdisk_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpViewObject
 */
#define statsdisk_wpViewObject(somSelf,hwndCnr,ulView,param) \
	WPObject_wpViewObject(somSelf,hwndCnr,ulView,param)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define statsdisk_wpAddDiskDetailsPage WPDisk_wpAddDiskDetailsPage
#define statsdisk_wpQueryDriveLockStatus WPDisk_wpQueryDriveLockStatus
#define statsdisk_wpEjectDisk WPDisk_wpEjectDisk
#define statsdisk_wpLockDrive WPDisk_wpLockDrive
#define statsdisk_wpQueryLogicalDrive WPDisk_wpQueryLogicalDrive
#define statsdisk_wpQueryRootFolder WPDisk_wpQueryRootFolder
#define statsdisk_wpSetCorrectDiskIcon WPDisk_wpSetCorrectDiskIcon
#define statsdisk_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define statsdisk_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define statsdisk_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define statsdisk_wpAddSettingsPages WPObject_wpAddSettingsPages
#define statsdisk_wpAddToObjUseList WPObject_wpAddToObjUseList
#define statsdisk_wpAllocMem WPObject_wpAllocMem
#define statsdisk_wpAppendObject WPObject_wpAppendObject
#define statsdisk_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define statsdisk_wpClose WPObject_wpClose
#define statsdisk_wpCnrInsertObject WPObject_wpCnrInsertObject
#define statsdisk_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define statsdisk_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define statsdisk_wpConfirmDelete WPObject_wpConfirmDelete
#define statsdisk_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define statsdisk_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define statsdisk_wpCopyObject WPObject_wpCopyObject
#define statsdisk_wpCreateAnother WPObject_wpCreateAnother
#define statsdisk_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define statsdisk_wpCreateShadowObject WPObject_wpCreateShadowObject
#define statsdisk_wpDelete WPObject_wpDelete
#define statsdisk_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define statsdisk_wpDisplayHelp WPObject_wpDisplayHelp
#define statsdisk_wpDisplayMenu WPObject_wpDisplayMenu
#define statsdisk_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define statsdisk_wpDraggedOverObject WPObject_wpDraggedOverObject
#define statsdisk_wpDragOver WPObject_wpDragOver
#define statsdisk_wpDrop WPObject_wpDrop
#define statsdisk_wpDroppedOnObject WPObject_wpDroppedOnObject
#define statsdisk_wpEndConversation WPObject_wpEndConversation
#define statsdisk_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define statsdisk_wpFindUseItem WPObject_wpFindUseItem
#define statsdisk_wpFormatDragItem WPObject_wpFormatDragItem
#define statsdisk_wpFree WPObject_wpFree
#define statsdisk_wpFreeMem WPObject_wpFreeMem
#define statsdisk_wpHide WPObject_wpHide
#define statsdisk_wpInitData WPObject_wpInitData
#define statsdisk_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define statsdisk_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define statsdisk_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define statsdisk_wpMoveObject WPObject_wpMoveObject
#define statsdisk_wpOpen WPObject_wpOpen
#define statsdisk_wpPrintObject WPObject_wpPrintObject
#define statsdisk_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define statsdisk_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define statsdisk_wpQueryConfirmations WPObject_wpQueryConfirmations
#define statsdisk_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define statsdisk_wpQueryDefaultView WPObject_wpQueryDefaultView
#define statsdisk_wpQueryDetailsData WPObject_wpQueryDetailsData
#define statsdisk_wpQueryError WPObject_wpQueryError
#define statsdisk_wpSetFolder WPObject_wpSetFolder
#define statsdisk_wpQueryFolder WPObject_wpQueryFolder
#define statsdisk_wpQueryIcon WPObject_wpQueryIcon
#define statsdisk_wpQueryIconData WPObject_wpQueryIconData
#define statsdisk_wpQueryMinWindow WPObject_wpQueryMinWindow
#define statsdisk_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define statsdisk_wpQueryStyle WPObject_wpQueryStyle
#define statsdisk_wpSetTaskRec WPObject_wpSetTaskRec
#define statsdisk_wpFindTaskRec WPObject_wpFindTaskRec
#define statsdisk_wpQueryTitle WPObject_wpQueryTitle
#define statsdisk_wpRegisterView WPObject_wpRegisterView
#define statsdisk_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define statsdisk_wpRender WPObject_wpRender
#define statsdisk_wpRenderComplete WPObject_wpRenderComplete
#define statsdisk_wpReplaceObject WPObject_wpReplaceObject
#define statsdisk_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define statsdisk_wpRestore WPObject_wpRestore
#define statsdisk_wpRestoreData WPObject_wpRestoreData
#define statsdisk_wpRestoreLong WPObject_wpRestoreLong
#define statsdisk_wpRestoreState WPObject_wpRestoreState
#define statsdisk_wpRestoreString WPObject_wpRestoreString
#define statsdisk_wpSaveData WPObject_wpSaveData
#define statsdisk_wpSaveImmediate WPObject_wpSaveImmediate
#define statsdisk_wpSaveDeferred WPObject_wpSaveDeferred
#define statsdisk_wpSaveLong WPObject_wpSaveLong
#define statsdisk_wpSaveState WPObject_wpSaveState
#define statsdisk_wpSaveString WPObject_wpSaveString
#define statsdisk_wpScanSetupString WPObject_wpScanSetupString
#define statsdisk_wpSetConcurrentView WPObject_wpSetConcurrentView
#define statsdisk_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define statsdisk_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define statsdisk_wpSetDefaultView WPObject_wpSetDefaultView
#define statsdisk_wpSetError WPObject_wpSetError
#define statsdisk_wpSetIconHandle WPObject_wpSetIconHandle
#define statsdisk_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define statsdisk_wpSetupOnce WPObject_wpSetupOnce
#define statsdisk_wpSetIcon WPObject_wpSetIcon
#define statsdisk_wpSetIconData WPObject_wpSetIconData
#define statsdisk_wpSetMinWindow WPObject_wpSetMinWindow
#define statsdisk_wpSetStyle WPObject_wpSetStyle
#define statsdisk_wpModifyStyle WPObject_wpModifyStyle
#define statsdisk_wpSetTitle WPObject_wpSetTitle
#define statsdisk_wpSetup WPObject_wpSetup
#define statsdisk_wpSwitchTo WPObject_wpSwitchTo
#define statsdisk_wpUnInitData WPObject_wpUnInitData
#define statsdisk_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define statsdisk_wpQueryHandle WPObject_wpQueryHandle
#define statsdisk_wpUnlockObject WPObject_wpUnlockObject
#define statsdisk_wpObjectReady WPObject_wpObjectReady
#define statsdisk_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define statsdisk_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define statsdisk_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define statsdisk_wpIsDeleteable WPObject_wpIsDeleteable
#define statsdisk_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define statsdisk_wpSetObjectID WPObject_wpSetObjectID
#define statsdisk_wpQueryObjectID WPObject_wpQueryObjectID
#define statsdisk_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define statsdisk_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define statsdisk_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define statsdisk_wpFindViewItem WPObject_wpFindViewItem
#define statsdisk_wpLockObject WPObject_wpLockObject
#define statsdisk_wpIsLocked WPObject_wpIsLocked
#define statsdisk_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define statsdisk_wpWaitForClose WPObject_wpWaitForClose
#define statsdisk_somDefaultInit SOMObject_somDefaultInit
#define statsdisk_somDestruct SOMObject_somDestruct
#define statsdisk_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define statsdisk_somDefaultAssign SOMObject_somDefaultAssign
#define statsdisk_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define statsdisk_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define statsdisk_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define statsdisk_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define statsdisk_somDefaultVAssign SOMObject_somDefaultVAssign
#define statsdisk_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define statsdisk_somInit SOMObject_somInit
#define statsdisk_somFree SOMObject_somFree
#define statsdisk_somUninit SOMObject_somUninit
#define statsdisk_somGetClass SOMObject_somGetClass
#define statsdisk_somGetClassName SOMObject_somGetClassName
#define statsdisk_somGetSize SOMObject_somGetSize
#define statsdisk_somIsA SOMObject_somIsA
#define statsdisk_somIsInstanceOf SOMObject_somIsInstanceOf
#define statsdisk_somRespondsTo SOMObject_somRespondsTo
#define statsdisk_somDispatch SOMObject_somDispatch
#define statsdisk_somClassDispatch SOMObject_somClassDispatch
#define statsdisk_somCastObj SOMObject_somCastObj
#define statsdisk_somResetObj SOMObject_somResetObj
#define statsdisk_somDispatchV SOMObject_somDispatchV
#define statsdisk_somDispatchL SOMObject_somDispatchL
#define statsdisk_somDispatchA SOMObject_somDispatchA
#define statsdisk_somDispatchD SOMObject_somDispatchD
#define statsdisk_somPrintSelf SOMObject_somPrintSelf
#define statsdisk_somDumpSelf SOMObject_somDumpSelf
#define statsdisk_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_statsdisk_h */

#ifndef SOM_M_statsdisk_h
#define SOM_M_statsdisk_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_statsdisk
#define M_statsdisk SOMObject
#endif
#include <wpdisk.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_statsdisk_HMODULE;
typedef
unsigned long  M_statsdisk_HPOINTER;
typedef
string  M_statsdisk_PSZ;

/*
 *  New class methods
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_statsdisk_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_statsdisk_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_statsdisk_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_statsdisk_MajorVersion 1
#define M_statsdisk_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_statsdiskNewClass statsdiskc
#pragma linkage(statsdiskc, system)
#define M_statsdiskClassData statsdiskd
#define M_statsdiskCClassData statsdiskx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_statsdisk_classObj M_statsdiskClassData.classObject
#define _M_statsdisk M_statsdisk_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_statsdiskNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_statsdiskNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_statsdiskClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
} SOMDLINK M_statsdiskClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_statsdiskCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_statsdiskCClassData;

/*
 * New and Renew macros for M_statsdisk
 */
#define M_statsdiskNew() \
   (_somNew(_M_statsdisk ? _M_statsdisk : M_statsdiskNewClass(M_statsdisk_MajorVersion, M_statsdisk_MinorVersion)))
#define M_statsdiskRenew(buf) \
   (_somRenew(_M_statsdisk ? _M_statsdisk : M_statsdiskNewClass(M_statsdisk_MajorVersion, M_statsdisk_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_statsdisk_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_statsdisk_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_statsdisk_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_statsdisk_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_statsdisk_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_statsdisk_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_statsdisk_wpclsNew M_WPObject_wpclsNew
#define M_statsdisk_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_statsdisk_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_statsdisk_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_statsdisk_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_statsdisk_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_statsdisk_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_statsdisk_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_statsdisk_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_statsdisk_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_statsdisk_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_statsdisk_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_statsdisk_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_statsdisk_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_statsdisk_wpclsSetError M_WPObject_wpclsSetError
#define M_statsdisk_wpclsQueryError M_WPObject_wpclsQueryError
#define M_statsdisk_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_statsdisk_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_statsdisk_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_statsdisk_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_statsdisk_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_statsdisk_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_statsdisk_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_statsdisk_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_statsdisk_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_statsdisk_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_statsdisk_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_statsdisk_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_statsdisk_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_statsdisk__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_statsdisk__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_statsdisk__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_statsdisk__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_statsdisk_somNew SOMClass_somNew
#define M_statsdisk_somNewNoInit SOMClass_somNewNoInit
#define M_statsdisk_somRenew SOMClass_somRenew
#define M_statsdisk_somRenewNoInit SOMClass_somRenewNoInit
#define M_statsdisk_somRenewNoZero SOMClass_somRenewNoZero
#define M_statsdisk_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_statsdisk_somAllocate SOMClass_somAllocate
#define M_statsdisk_somDeallocate SOMClass_somDeallocate
#define M_statsdisk__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_statsdisk__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_statsdisk_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_statsdisk_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_statsdisk_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_statsdisk_somInitClass SOMClass_somInitClass
#define M_statsdisk_somInitMIClass SOMClass_somInitMIClass
#define M_statsdisk_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_statsdisk_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_statsdisk_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_statsdisk_somClassReady SOMClass_somClassReady
#define M_statsdisk_somGetApplyStub SOMClass_somGetApplyStub
#define M_statsdisk_somGetClassData SOMClass_somGetClassData
#define M_statsdisk_somSetClassData SOMClass_somSetClassData
#define M_statsdisk_somGetClassMtab SOMClass_somGetClassMtab
#define M_statsdisk_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_statsdisk_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_statsdisk_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_statsdisk_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_statsdisk_somGetMemberToken SOMClass_somGetMemberToken
#define M_statsdisk_somGetMethodData SOMClass_somGetMethodData
#define M_statsdisk_somGetRdStub SOMClass_somGetRdStub
#define M_statsdisk_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_statsdisk_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_statsdisk_somGetMethodToken SOMClass_somGetMethodToken
#define M_statsdisk_somGetName SOMClass_somGetName
#define M_statsdisk_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_statsdisk_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_statsdisk_somGetNumMethods SOMClass_somGetNumMethods
#define M_statsdisk_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_statsdisk_somGetParent SOMClass_somGetParent
#define M_statsdisk_somGetParents SOMClass_somGetParents
#define M_statsdisk_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_statsdisk_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_statsdisk_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_statsdisk_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_statsdisk_somFindMethod SOMClass_somFindMethod
#define M_statsdisk_somFindMethodOk SOMClass_somFindMethodOk
#define M_statsdisk_somFindSMethod SOMClass_somFindSMethod
#define M_statsdisk_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_statsdisk_somLookupMethod SOMClass_somLookupMethod
#define M_statsdisk_somCheckVersion SOMClass_somCheckVersion
#define M_statsdisk_somDescendedFrom SOMClass_somDescendedFrom
#define M_statsdisk_somSupportsMethod SOMClass_somSupportsMethod
#define M_statsdisk_somDefinedMethod SOMClass_somDefinedMethod
#define M_statsdisk_somOverrideMtab SOMClass_somOverrideMtab
#define M_statsdisk_somDefaultInit SOMObject_somDefaultInit
#define M_statsdisk_somDestruct SOMObject_somDestruct
#define M_statsdisk_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_statsdisk_somDefaultAssign SOMObject_somDefaultAssign
#define M_statsdisk_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_statsdisk_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_statsdisk_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_statsdisk_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_statsdisk_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_statsdisk_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_statsdisk_somInit SOMObject_somInit
#define M_statsdisk_somFree SOMObject_somFree
#define M_statsdisk_somUninit SOMObject_somUninit
#define M_statsdisk_somGetClass SOMObject_somGetClass
#define M_statsdisk_somGetClassName SOMObject_somGetClassName
#define M_statsdisk_somGetSize SOMObject_somGetSize
#define M_statsdisk_somIsA SOMObject_somIsA
#define M_statsdisk_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_statsdisk_somRespondsTo SOMObject_somRespondsTo
#define M_statsdisk_somDispatch SOMObject_somDispatch
#define M_statsdisk_somClassDispatch SOMObject_somClassDispatch
#define M_statsdisk_somCastObj SOMObject_somCastObj
#define M_statsdisk_somResetObj SOMObject_somResetObj
#define M_statsdisk_somDispatchV SOMObject_somDispatchV
#define M_statsdisk_somDispatchL SOMObject_somDispatchL
#define M_statsdisk_somDispatchA SOMObject_somDispatchA
#define M_statsdisk_somDispatchD SOMObject_somDispatchD
#define M_statsdisk_somPrintSelf SOMObject_somPrintSelf
#define M_statsdisk_somDumpSelf SOMObject_somDumpSelf
#define M_statsdisk_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_statsdisk_h */
