/******************************************************************************/
/*                                                                            */
/* Program: STATINST.EXE                                                      */
/*                                                                            */
/* Description: Description                                                   */
/*                                                                            */
/* File Name : NPATH.H                                                        */
/*                                                                            */
/* Author : GARY L. ROBINSON                                                  */
/*                                                                            */
/* Copyright 1997 Copyright notice                                            */
/*                                                                            */
/* Generated using VisPro/C serial number VPC5013754                          */
/*                                                                            */
/******************************************************************************/

#ifndef NPATHWINDOW_H
#define NPATHWINDOW_H

 /* ##START Form.39 Form header definitions */
 /* ##END Form header definitions */
HWND OpenNPATH(HWND hwndOwner, PVOID pInfo);

#define ID_FORMTIMER 100   /* Used for timer events */
#endif